import fs from "node:fs";
import { join } from "node:path";
import { z } from "zod";
import { cliContractRegistry } from "@/cli/commands/run";
import { introspectContracts } from "@/cli/command-contract/introspection";

const CLI_CONTRACT_ARTIFACT_NAMES = [
	"cli-command-audit.md",
	"command-contract-proof.json",
	"command-contract-proof.md",
] as const;

/** One audit cell: a sentence, or a list rendered as one. */
const AuditCellSchema = z.union([z.string(), z.array(z.string())]);

/** The audit columns this renderer prints; the canonical JSON carries more. */
const AuditEntrySchema = z.object({
	path: AuditCellSchema,
	classification: AuditCellSchema,
	parserOwner: AuditCellSchema,
	stdout: AuditCellSchema,
	result: AuditCellSchema,
	prerequisites: AuditCellSchema,
	relationships: AuditCellSchema,
	semantics: AuditCellSchema,
	ordering: AuditCellSchema,
	nextFields: AuditCellSchema,
	workflow: AuditCellSchema,
});

const AuditWorkflowSchema = z.object({
	name: z.string(),
	classification: z.string(),
	decision: z.string(),
	evidence: z.string(),
	commands: z.array(z.string()),
	followUpTask: z.string().nullable().optional(),
});

const CliAuditSchema = z.object({
	reviewedBase: z.string(),
	surface: z.object({ commands: z.number(), subcommands: z.number(), paths: z.number() }),
	entries: z.array(AuditEntrySchema),
	workflows: z.array(AuditWorkflowSchema),
});

/**
 * Renders one audit value as a Markdown table cell, escaping the pipe and
 * flattening newlines so a sentence cannot break the table it sits in.
 * @param value - The audit value, a sentence or a list.
 * @returns The cell text.
 */
function cell(value: z.infer<typeof AuditCellSchema>): string {
	return (Array.isArray(value) ? value.join("; ") : value)
		.replaceAll("|", "\\|")
		.replaceAll("\n", " ");
}

/**
 * Formats generated content the way the repository formats its own files, so
 * a generated artifact never differs from a committed one by whitespace alone.
 * @param root - The repository root.
 * @param name - The generated file's name, which decides how it is formatted.
 * @param content - The content to format.
 * @returns The formatted content.
 * @throws {Error} When the formatter refuses the content.
 */
function format(root: string, name: string, content: string): string {
	const formatted = Bun.spawnSync(
		["bunx", "oxfmt", "--stdin-filepath", join(root, "docs", "design", "generated", name)],
		{
			cwd: root,
			stdin: new TextEncoder().encode(content),
			stdout: "pipe",
			stderr: "pipe",
		},
	);
	if (formatted.exitCode !== 0) {
		throw new Error(`Could not format ${name}: ${formatted.stderr.toString()}`);
	}
	return formatted.stdout.toString();
}

/**
 * Renders every generated CLI contract artifact from the two sources that
 * decide them: the reviewed audit JSON, and the live command registry with the
 * public metadata its contracts declare.
 * @param root - The repository root.
 * @returns The formatted artifacts by file name, with the audit, proof, registry and routes they were built from.
 * @throws {Error} When the audit JSON does not match the shape this renderer prints.
 */
async function renderCliContractArtifacts(root: string) {
	const audit = CliAuditSchema.parse(
		JSON.parse(fs.readFileSync(join(root, "docs", "design", "cli-command-audit.json"), "utf8")),
	);
	const registry = cliContractRegistry();
	const proof = introspectContracts(registry);
	const routes = registry.map(
		({ name, parent, classification, handlerOwner, parserOwner, bare, childDiscovery }) => ({
			name,
			parent,
			classification,
			handlerOwner,
			parserOwner,
			...(bare ? { bare } : {}),
			...(childDiscovery ? { childDiscovery } : {}),
		}),
	);

	const auditMarkdown = [
		"<!-- Generated from ../cli-command-audit.json. Do not edit this file. -->",
		"# CLI command audit",
		"",
		`Reviewed base: \`${audit.reviewedBase}\`.`,
		"",
		`The canonical JSON records ${audit.surface.commands} commands, ${audit.surface.subcommands} subcommands, and ${audit.surface.paths} public paths.`,
		"",
		"| Path | Class | Parser | Output/result | Prerequisites and relationships | Semantics and ordering | Next fields | Workflow |",
		"| --- | --- | --- | --- | --- | --- | --- | --- |",
		...audit.entries.map(
			(entry) =>
				`| \`${cell(entry.path)}\` | ${cell(entry.classification)} | ${cell(entry.parserOwner)} | ${cell(entry.stdout)}. ${cell(entry.result)} | ${cell(entry.prerequisites)}. ${cell(entry.relationships)} | ${cell(entry.semantics)}. ${cell(entry.ordering)} | ${cell(entry.nextFields)} | ${cell(entry.workflow)} |`,
		),
		"",
		"## Workflow deletion test",
		"",
		...audit.workflows.flatMap((workflow) => [
			`### ${workflow.name}`,
			"",
			`Classification: ${workflow.classification}. Decision: ${workflow.decision}.`,
			"",
			workflow.evidence,
			"",
			`Commands: ${workflow.commands.map((command) => `\`${command}\``).join(", ")}. Follow-up: ${workflow.followUpTask ?? "none approved"}.`,
			"",
		]),
	].join("\n");

	const proofJson = `${JSON.stringify(
		{
			schemaVersion: 7,
			generatedFrom: "src/cli/commands/run.ts",
			routes,
			contracts: proof,
		},
		null,
		2,
	)}\n`;

	const proofMarkdown = [
		"<!-- Generated from the run.ts registry and public CommandContract metadata. -->",
		"# Command contract proof reference",
		"",
	];
	for (const contract of proof) {
		proofMarkdown.push(
			`## ${contract.path.join(" ")}`,
			"",
			contract.description,
			"",
			`Classification: ${contract.classification}.`,
			"",
			"Usage:",
			"",
			"```text",
			`archboard ${contract.usage}`,
			"```",
			"",
			`Output: ${contract.output.map((output) => `${output.mode} (${output.description})`).join("; ")}.`,
			"",
			`Prerequisites: ${contract.prerequisites.join(", ") || "none"}. Effects: ${contract.effects.join(", ") || "none"}.`,
			"",
			"REST relationships:",
			"",
			...contract.relationships.map(
				(relationship) =>
					`- ${relationship.method} \`${relationship.path}\`, ${relationship.cardinality}. ${relationship.description}`,
			),
			"",
			"Public result JSON Schema:",
			"",
			"```json",
			JSON.stringify(contract.result, null, 2),
			"```",
			"",
		);
	}

	const rawArtifacts = new Map<string, string>([
		["cli-command-audit.md", `${auditMarkdown}\n`],
		["command-contract-proof.json", proofJson],
		["command-contract-proof.md", `${proofMarkdown.join("\n")}\n`],
	]);
	const artifacts = new Map(
		[...rawArtifacts].map(([name, content]) => [name, format(root, name, content)]),
	);
	return { artifacts, audit, proof, registry, routes };
}

export { CLI_CONTRACT_ARTIFACT_NAMES, renderCliContractArtifacts };
