import fs from "node:fs";
import { join } from "node:path";
import { cliContractRegistry } from "../commands/run.js";
import { introspectContracts } from "./introspection.js";

export const CLI_CONTRACT_ARTIFACT_NAMES = [
	"cli-command-audit.md",
	"command-contract-proof.json",
	"command-contract-proof.md",
] as const;

interface AuditEntry {
	path: unknown;
	parserOwner: unknown;
	stdout: unknown;
	result: unknown;
	prerequisites: unknown;
	relationships: unknown;
	semantics: unknown;
	ordering: unknown;
	nextFields: unknown;
	workflow: unknown;
}

interface AuditWorkflow {
	name: string;
	classification: string;
	decision: string;
	evidence: string;
	commands: string[];
	followUpTask?: string;
}

interface CliAudit {
	reviewedBase: string;
	surface: { commands: number; subcommands: number; paths: number };
	entries: AuditEntry[];
	workflows: AuditWorkflow[];
}

const cell = (value: unknown): string =>
	(Array.isArray(value) ? value.join("; ") : String(value ?? ""))
		.replaceAll("|", "\\|")
		.replaceAll("\n", " ");

function format(root: string, name: string, content: string): string {
	const formatted = Bun.spawnSync(
		["bunx", "oxfmt", "--stdin-filepath", join(root, "docs", "design", "generated", name)],
		{
			cwd: root,
			stdin: new TextEncoder().encode(content),
			stdout: "pipe",
			stderr: "pipe",
		},
	);
	if (formatted.exitCode !== 0) {
		throw new Error(`Could not format ${name}: ${formatted.stderr.toString()}`);
	}
	return formatted.stdout.toString();
}

export async function renderCliContractArtifacts(root: string) {
	const audit = JSON.parse(
		fs.readFileSync(join(root, "docs", "design", "cli-command-audit.json"), "utf8"),
	) as CliAudit;
	const registry = cliContractRegistry();
	const proof = introspectContracts(registry);
	const routes = registry.map(
		({ name, parent, handlerOwner, parserOwner, bare, childDiscovery }) => ({
			name,
			parent,
			handlerOwner,
			parserOwner,
			...(bare ? { bare } : {}),
			...(childDiscovery ? { childDiscovery } : {}),
		}),
	);

	const auditMarkdown = [
		"<!-- Generated from ../cli-command-audit.json. Do not edit this file. -->",
		"# CLI command audit",
		"",
		`Reviewed base: \`${audit.reviewedBase}\`.`,
		"",
		`The canonical JSON records ${audit.surface.commands} commands, ${audit.surface.subcommands} subcommands, and ${audit.surface.paths} public paths.`,
		"",
		"| Path | Parser | Output/result | Prerequisites and relationships | Semantics and ordering | Next fields | Workflow |",
		"| --- | --- | --- | --- | --- | --- | --- |",
		...audit.entries.map(
			(entry) =>
				`| \`${cell(entry.path)}\` | ${cell(entry.parserOwner)} | ${cell(entry.stdout)}. ${cell(entry.result)} | ${cell(entry.prerequisites)}. ${cell(entry.relationships)} | ${cell(entry.semantics)}. ${cell(entry.ordering)} | ${cell(entry.nextFields)} | ${cell(entry.workflow)} |`,
		),
		"",
		"## Workflow deletion test",
		"",
		...audit.workflows.flatMap((workflow) => [
			`### ${workflow.name}`,
			"",
			`Classification: ${workflow.classification}. Decision: ${workflow.decision}.`,
			"",
			workflow.evidence,
			"",
			`Commands: ${workflow.commands.map((command) => `\`${command}\``).join(", ")}. Follow-up: ${workflow.followUpTask ?? "none approved"}.`,
			"",
		]),
	].join("\n");

	const proofJson =
		JSON.stringify(
			{
				schemaVersion: 6,
				generatedFrom: "src/cli/commands/run.ts",
				routes,
				contracts: proof,
			},
			null,
			2,
		) + "\n";

	const proofMarkdown = [
		"<!-- Generated from the run.ts registry and public CommandContract metadata. -->",
		"# Command contract proof reference",
		"",
	];
	for (const contract of proof) {
		proofMarkdown.push(
			`## ${contract.path.join(" ")}`,
			"",
			contract.description,
			"",
			"Usage:",
			"",
			"```text",
			`archboard ${contract.usage}`,
			"```",
			"",
			`Output: ${contract.output.map((output) => `${output.mode} (${output.description})`).join("; ")}.`,
			"",
			`Prerequisites: ${contract.prerequisites.join(", ") || "none"}. Effects: ${contract.effects.join(", ") || "none"}.`,
			"",
			"REST relationships:",
			"",
			...contract.relationships.map(
				(relationship) =>
					`- ${relationship.method} \`${relationship.path}\`, ${relationship.cardinality}. ${relationship.description}`,
			),
			"",
			"Public result JSON Schema:",
			"",
			"```json",
			JSON.stringify(contract.result, null, 2),
			"```",
			"",
		);
	}

	const rawArtifacts = new Map<string, string>([
		["cli-command-audit.md", auditMarkdown + "\n"],
		["command-contract-proof.json", proofJson],
		["command-contract-proof.md", proofMarkdown.join("\n") + "\n"],
	]);
	const artifacts = new Map(
		[...rawArtifacts].map(([name, content]) => [name, format(root, name, content)]),
	);
	return { artifacts, audit, proof, registry, routes };
}
