import type { BedrockSetupParams, ClientRequestParams, ClientRequestPayloads } from "../index.js";

const textInput: Extract<ClientRequestParams<"turn/start">["input"][number], { type: "text" }> = {
	type: "text",
	text: "Inspect the architecture",
	text_elements: [{ byteRange: { start: 0, end: 7 }, placeholder: "Inspect" }],
};
const environment: NonNullable<ClientRequestParams<"turn/start">["environments"]>[number] = {
	environmentId: "environment-1",
	cwd: "/repo",
	runtimeWorkspaceRoots: ["/repo"],
};
const collaborationMode = {
	mode: "default",
	settings: {
		model: "gpt-5.6-luna",
		reasoning_effort: "medium",
		developer_instructions: "Keep the request bounded.",
	},
} as const;

const COMPLETE_CLIENT_REQUEST_FIXTURES = {
	initialize: {
		clientInfo: { name: "archboard", title: "archboard canvas", version: "0.1.0" },
		capabilities: {
			experimentalApi: true,
			requestAttestation: false,
			mcpServerOpenaiFormElicitation: true,
			optOutNotificationMethods: [],
			extensions: {},
		},
	},
	"config/read": { includeLayers: true, cwd: "/repo" },
	"configRequirements/read": undefined,
	"account/read": { refreshToken: true },
	"account/login/start": {
		type: "amazonBedrockAccessKeys",
		accessKeyId: "access-key",
		secretAccessKey: "secret-key",
		sessionToken: "session-token",
		region: "eu-west-1",
	},
	"account/login/cancel": { loginId: "login-1" },
	"account/logout": undefined,
	"model/list": { cursor: "model-cursor", limit: 20, includeHidden: true },
	"thread/start": {
		model: "gpt-5.6-luna",
		modelProvider: "openai",
		allowProviderModelFallback: false,
		serviceTier: "priority",
		cwd: "/repo",
		runtimeWorkspaceRoots: ["/repo"],
		approvalPolicy: "on-request",
		approvalsReviewer: "user",
		sandbox: "workspace-write",
		config: { features: { realtime_conversation: true } },
		serviceName: "archboard",
		baseInstructions: "base",
		developerInstructions: "developer",
		personality: "pragmatic",
		multiAgentMode: { custom: "explicit" },
		ephemeral: false,
		historyMode: "paginated",
		sessionStartSource: "startup",
		threadSource: "archboard",
		projectId: "project-1",
		environments: [environment],
		dynamicTools: [
			{
				type: "function",
				name: "inspect",
				description: "Inspect one target.",
				inputSchema: { type: "object" },
				deferLoading: false,
			},
			{
				type: "namespace",
				name: "archboard_app",
				description: "Coordinate work.",
				tools: [
					{
						type: "function",
						name: "read",
						description: "Read one target.",
						inputSchema: { type: "object" },
						deferLoading: false,
					},
				],
			},
		],
		selectedCapabilityRoots: [
			{
				id: "capability-1",
				location: { type: "environment", environmentId: "environment-1", path: "/repo" },
			},
		],
		mockExperimentalField: "fixture",
		experimentalRawEvents: false,
	},
	"thread/fork": {
		threadId: "thread-1",
		beforeTurnId: "turn-1",
		path: null,
		model: "gpt-5.6-luna",
		modelProvider: "openai",
		serviceTier: "priority",
		cwd: "/repo",
		runtimeWorkspaceRoots: ["/repo"],
		approvalPolicy: "on-request",
		approvalsReviewer: "user",
		sandbox: "workspace-write",
		config: { feature: true },
		baseInstructions: "base",
		developerInstructions: "developer",
		ephemeral: false,
		threadSource: "archboard",
		excludeTurns: true,
		deferGoalContinuation: false,
	},
	"thread/list": {
		cursor: "thread-cursor",
		limit: 50,
		sortKey: "recency_at",
		sortDirection: "desc",
		modelProviders: ["openai"],
		sourceKinds: ["cli", "appServer"],
		archived: false,
		sectionId: "section-1",
		projectId: "project-1",
		cwd: ["/repo"],
		useStateDbOnly: false,
		searchTerm: "architecture",
		parentThreadId: "parent-thread",
	},
	"thread/loaded/list": { cursor: "loaded-cursor", limit: 100 },
	"thread/read": { threadId: "thread-1", includeTurns: false },
	"thread/turns/list": {
		threadId: "thread-1",
		cursor: "turn-cursor",
		limit: 10,
		sortDirection: "desc",
		itemsView: "summary",
	},
	"thread/items/list": {
		threadId: "thread-1",
		turnId: "turn-1",
		cursor: "item-cursor",
		limit: 100,
		sortDirection: "asc",
	},
	"thread/delete": { threadId: "thread-1" },
	"thread/settings/update": {
		threadId: "thread-1",
		cwd: "/repo",
		approvalPolicy: "on-request",
		approvalsReviewer: "user",
		sandboxPolicy: {
			type: "workspaceWrite",
			writableRoots: ["/repo"],
			networkAccess: true,
			excludeTmpdirEnvVar: false,
			excludeSlashTmp: false,
		},
		model: "gpt-5.6-luna",
		serviceTier: "priority",
		effort: "medium",
		summary: "concise",
		collaborationMode,
		multiAgentMode: "explicitRequestOnly",
		personality: "pragmatic",
	},
	"turn/start": {
		threadId: "thread-1",
		clientUserMessageId: "message-1",
		input: [textInput],
		turnTrigger: "archboard",
		toolOutput: { name: "inspect", namespace: "archboard_app", output: "complete" },
		responsesapiClientMetadata: { producer: "archboard" },
		additionalContext: { archboard: { value: "{}", kind: "application" } },
		environments: [environment],
		cwd: "/repo",
		runtimeWorkspaceRoots: ["/repo"],
		approvalPolicy: "on-request",
		approvalsReviewer: "user",
		sandboxPolicy: { type: "readOnly", networkAccess: false },
		model: "gpt-5.6-luna",
		serviceTier: "priority",
		serviceTierForTurn: "default",
		effort: "medium",
		summary: "concise",
		personality: "pragmatic",
		outputSchema: { type: "object" },
		collaborationMode,
		multiAgentMode: "explicitRequestOnly",
		cyberAccessProgram: "standard",
	},
	"turn/steer": {
		threadId: "thread-1",
		clientUserMessageId: "message-2",
		input: [textInput],
		responsesapiClientMetadata: { producer: "archboard" },
		additionalContext: { archboard: { value: "{}", kind: "application" } },
		expectedTurnId: "turn-1",
	},
	"turn/interrupt": { threadId: "thread-1", turnId: "turn-1" },
	"thread/queue/add": {
		threadId: "thread-1",
		input: [textInput],
		clientUserMessageId: "message-3",
	},
	"thread/queue/list": { threadId: "thread-1", cursor: "queue-cursor", limit: 25 },
	"thread/queue/update": {
		threadId: "thread-1",
		queuedSubmissionId: "queue-1",
		input: [textInput],
	},
	"thread/queue/delete": { threadId: "thread-1", queuedSubmissionId: "queue-1" },
	"thread/queue/reorder": {
		threadId: "thread-1",
		queuedSubmissionIds: ["queue-2", "queue-1"],
	},
	"thread/queue/start": { threadId: "thread-1", queuedSubmissionId: "queue-1" },
	"thread/inject_items": {
		threadId: "thread-1",
		items: [{ type: "message", role: "developer", content: [] }],
	},
	"thread/realtime/start": {
		threadId: "thread-1",
		clientManagedHandoffs: false,
		delegationAckFiller: true,
		flushTranscriptTailOnSessionEnd: true,
		codexResponsesAsItems: false,
		codexResponseItemPrefix: "Codex",
		codexResponseHandoffMode: "bemTags",
		codexResponseHandoffChannelPrefixes: { final: ["[FINAL]"] },
		model: "gpt-realtime",
		outputModality: "audio",
		includeStartupContext: true,
		initialItems: [{ role: "developer", text: "Current architecture context" }],
		realtimeStartInstructions: "Start realtime.",
		realtimeEndInstructions: "Finish the sentence.",
		prompt: "Discuss the architecture.",
		realtimeSessionId: "realtime-1",
		transport: { type: "webrtc", sdp: "offer" },
		version: "v3",
		voice: "breeze",
	},
	"thread/realtime/appendText": { threadId: "thread-1", text: "hello", role: "user" },
	"thread/realtime/appendSpeech": { threadId: "thread-1", text: "hello" },
	"thread/realtime/stop": { threadId: "thread-1" },
	"thread/timeline/list": { threadId: "thread-1", cursor: "timeline-cursor", limit: 50 },
} satisfies ClientRequestPayloads;

const LOGIN_ACCOUNT_FIXTURES = [
	{ type: "apiKey", apiKey: "api-key" },
	{
		type: "chatgpt",
		codexStreamlinedLogin: true,
		useHostedLoginSuccessPage: true,
		appBrand: "codex",
	},
	{ type: "chatgptDeviceCode" },
	{
		type: "chatgptAuthTokens",
		accessToken: "access-token",
		chatgptAccountId: "account-1",
		chatgptPlanType: "pro",
	},
	{ type: "amazonBedrock", apiKey: "api-key", region: "eu-west-1" },
	{
		type: "amazonBedrockAccessKeys",
		accessKeyId: "access-key",
		secretAccessKey: "secret-key",
		sessionToken: null,
		region: "eu-west-1",
	},
] satisfies readonly ClientRequestParams<"account/login/start">[];

const BEDROCK_SETUP_FIXTURES = [
	{ type: "profile", profile: "archboard", region: "eu-west-1" },
	{ type: "environment", region: "eu-west-1" },
] satisfies readonly BedrockSetupParams[];

export {
	BEDROCK_SETUP_FIXTURES,
	COMPLETE_CLIENT_REQUEST_FIXTURES,
	LOGIN_ACCOUNT_FIXTURES,
};
