import type {
	ClientNotificationMethod,
	ResponseMethod,
	ServerNotificationMethod,
	ServerRequestMethod,
} from "../index.js";

export const threadItemFixture = {
	type: "userMessage",
	id: "item-1",
	clientId: null,
	content: [{ type: "text", text: "hello", text_elements: [] }],
};

export const turnFixture = {
	id: "turn-1",
	items: [threadItemFixture],
	itemsView: "full",
	status: "completed",
	error: null,
	startedAt: 1,
	completedAt: 2,
	durationMs: 1,
};

export const threadFixture = {
	id: "thread-1",
	extra: {},
	sessionId: "session-1",
	forkedFromId: null,
	parentThreadId: null,
	preview: "hello",
	ephemeral: false,
	section: null,
	sectionEnteredAt: null,
	projectId: null,
	historyMode: "paginated",
	modelProvider: "openai",
	createdAt: 1,
	updatedAt: 2,
	recencyAt: null,
	status: { type: "idle" },
	path: null,
	cwd: "/tmp/archboard",
	cliVersion: "0.151.0",
	source: "appServer",
	canAcceptDirectInput: true,
	threadSource: "archboard",
	agentNickname: null,
	agentRole: null,
	gitInfo: null,
	name: null,
	turns: [turnFixture],
};

export const configFixture = {
	model: null,
	review_model: null,
	model_context_window: null,
	model_auto_compact_token_limit: null,
	model_auto_compact_token_limit_scope: null,
	model_provider: null,
	approval_policy: null,
	approvals_reviewer: null,
	sandbox_mode: null,
	sandbox_workspace_write: null,
	forced_chatgpt_workspace_id: null,
	forced_login_method: null,
	web_search: null,
	tools: null,
	instructions: null,
	developer_instructions: null,
	compact_prompt: null,
	model_reasoning_effort: null,
	model_reasoning_summary: null,
	model_verbosity: null,
	service_tier: null,
	analytics: null,
	apps: null,
	browser_use: null,
	computer_use: null,
	desktop: null,
};

export const modelFixture = {
	id: "gpt-5.6-luna",
	model: "gpt-5.6-luna",
	upgrade: null,
	upgradeInfo: null,
	availabilityNux: null,
	displayName: "Luna",
	description: "fixture",
	modelSpecialty: null,
	hidden: false,
	supportedReasoningEfforts: [{ reasoningEffort: "medium", description: "fixture" }],
	defaultReasoningEffort: "medium",
	inputModalities: ["text"],
	supportsPersonality: false,
	multiAgentVersion: null,
	additionalSpeedTiers: [],
	serviceTiers: [],
	defaultServiceTier: null,
	isDefault: true,
};

export const queuedSubmissionFixture = {
	id: "queue-1",
	input: [{ type: "text", text: "queued", text_elements: [] }],
	clientUserMessageId: "client-queue-1",
};

const threadStartResponseFixture = {
	thread: threadFixture,
	model: "gpt-5.6-luna",
	modelProvider: "openai",
	serviceTier: null,
	cwd: "/tmp/archboard",
	runtimeWorkspaceRoots: ["/tmp/archboard"],
	instructionSources: [],
	approvalPolicy: "never",
	approvalsReviewer: "user",
	sandbox: { type: "dangerFullAccess" },
	activePermissionProfile: null,
	reasoningEffort: "medium",
	multiAgentMode: "explicitRequestOnly",
};

export const responseFixtures: Record<ResponseMethod, unknown> = {
	initialize: {
		userAgent: "Codex Desktop/0.151.0",
		codexHome: "/tmp/codex",
		platformFamily: "unix",
		platformOs: "linux",
	},
	"config/read": { config: configFixture, origins: {}, layers: null },
	"configRequirements/read": { requirements: null },
	"account/read": {
		account: { type: "chatgpt", email: null, planType: "pro" },
		requiresOpenaiAuth: true,
	},
	"account/login/start": {
		type: "chatgpt",
		loginId: "login-1",
		authUrl: "https://example.test/login",
	},
	"account/login/cancel": { status: "canceled" },
	"account/logout": {},
	"model/list": { data: [modelFixture], nextCursor: null },
	"thread/start": threadStartResponseFixture,
	"thread/fork": threadStartResponseFixture,
	"thread/list": { data: [threadFixture], nextCursor: null, backwardsCursor: null },
	"thread/loaded/list": { data: ["thread-1"], nextCursor: null },
	"thread/read": { thread: threadFixture },
	"thread/turns/list": { data: [turnFixture], nextCursor: null, backwardsCursor: null },
	"thread/items/list": {
		data: [{ turnId: "turn-1", item: threadItemFixture }],
		nextCursor: null,
		backwardsCursor: null,
	},
	"thread/delete": {},
	"thread/settings/update": {},
	"turn/start": { turn: turnFixture },
	"turn/steer": { turnId: "turn-1" },
	"turn/interrupt": {},
	"thread/queue/add": { queuedSubmission: queuedSubmissionFixture },
	"thread/queue/list": { data: [queuedSubmissionFixture], nextCursor: null },
	"thread/queue/update": { queuedSubmission: queuedSubmissionFixture },
	"thread/queue/delete": { deleted: true },
	"thread/queue/reorder": {},
	"thread/queue/start": { turn: turnFixture },
	"thread/inject_items": {},
	"thread/realtime/start": {},
	"thread/realtime/appendText": {},
	"thread/realtime/appendSpeech": {},
	"thread/realtime/stop": {},
	"thread/timeline/list": {
		data: [{ type: "turnStarted", position: 1, turnId: "turn-1", startedAt: 1 }],
		nextCursor: null,
		activeRealtimeSessionAtPageStart: null,
	},
	"currentTime/read": { currentTimeAt: 1 },
};

export const serverRequestFixtures: Record<ServerRequestMethod, unknown> = {
	"item/commandExecution/requestApproval": {
		kind: "command",
		threadId: "thread-1",
		turnId: "turn-1",
		itemId: "item-1",
		startedAtMs: 1000,
		environmentId: null,
	},
	"item/fileChange/requestApproval": {
		threadId: "thread-1",
		turnId: "turn-1",
		itemId: "item-1",
		startedAtMs: 1000,
	},
	"item/tool/requestUserInput": {
		threadId: "thread-1",
		turnId: "turn-1",
		itemId: "item-1",
		questions: [],
		isBlocking: true,
		autoResolutionMs: null,
	},
	"mcpServer/elicitation/request": {
		threadId: "thread-1",
		turnId: null,
		serverName: "fixture",
		mode: "form",
		_meta: null,
		message: "fixture",
		requestedSchema: { type: "object", properties: {} },
	},
	"item/permissions/requestApproval": {
		threadId: "thread-1",
		turnId: "turn-1",
		itemId: "item-1",
		environmentId: null,
		startedAtMs: 1000,
		cwd: "/tmp/archboard",
		reason: null,
		permissions: { network: null, fileSystem: null },
	},
	"item/tool/call": {
		threadId: "thread-1",
		turnId: "turn-1",
		callId: "call-1",
		namespace: "archboard_app",
		tool: "inspect",
		arguments: { board: "fixture" },
	},
	"account/chatgptAuthTokens/refresh": { reason: "unauthorized", previousAccountId: null },
	"attestation/generate": {},
	"currentTime/read": { threadId: "thread-1" },
	applyPatchApproval: {
		conversationId: "thread-1",
		callId: "call-1",
		fileChanges: { "/tmp/archboard/file": { type: "add", content: "fixture" } },
		reason: null,
		grantRoot: null,
	},
	execCommandApproval: {
		conversationId: "thread-1",
		callId: "call-1",
		approvalId: null,
		command: ["true"],
		cwd: "/tmp/archboard",
		reason: null,
		parsedCmd: [],
	},
};

const baseThreadNotification = { threadId: "thread-1" };
const baseTurnDelta = { threadId: "thread-1", turnId: "turn-1", itemId: "item-1", delta: "delta" };

export const serverNotificationFixtures: Partial<Record<ServerNotificationMethod, unknown>> = {
	error: {
		error: {
			message: "fixture",
			codexErrorInfo: null,
			additionalDetails: null,
			misalignment: null,
		},
		willRetry: false,
		...baseThreadNotification,
		turnId: "turn-1",
	},
	"thread/started": { thread: threadFixture },
	"thread/status/changed": { ...baseThreadNotification, status: { type: "idle" } },
	"thread/archived": baseThreadNotification,
	"thread/deleted": baseThreadNotification,
	"thread/unarchived": baseThreadNotification,
	"thread/closed": baseThreadNotification,
	"thread/reverted": baseThreadNotification,
	"thread/name/updated": { ...baseThreadNotification, threadName: "Fixture" },
	"thread/goal/updated": {
		...baseThreadNotification,
		turnId: null,
		goal: {
			threadId: "thread-1",
			objective: "fixture",
			status: "active",
			tokenBudget: null,
			tokensUsed: 0,
			timeUsedSeconds: 0,
			createdAt: 1,
			updatedAt: 1,
		},
	},
	"thread/goal/cleared": baseThreadNotification,
	"thread/queue/changed": baseThreadNotification,
	"project/changed": { projectId: "project-1", changeType: "updated" },
	"thread/project/updated": { ...baseThreadNotification, projectId: null },
	"thread/environment/connected": { ...baseThreadNotification, environmentId: "env-1" },
	"thread/environment/disconnected": { ...baseThreadNotification, environmentId: "env-1" },
	"thread/settings/updated": {
		...baseThreadNotification,
		threadSettings: {
			cwd: "/tmp/archboard",
			approvalPolicy: "never",
			approvalsReviewer: "user",
			sandboxPolicy: { type: "dangerFullAccess" },
			activePermissionProfile: null,
			model: "gpt-5.6-luna",
			modelProvider: "openai",
			serviceTier: null,
			effort: "medium",
			summary: "auto",
			collaborationMode: {
				mode: "default",
				settings: {
					model: "gpt-5.6-luna",
					reasoning_effort: "medium",
					developer_instructions: null,
				},
			},
			multiAgentMode: "explicitRequestOnly",
			personality: null,
		},
	},
	"thread/tokenUsage/updated": {
		...baseThreadNotification,
		turnId: "turn-1",
		tokenUsage: {
			total: {
				totalTokens: 1,
				inputTokens: 1,
				cachedInputTokens: 0,
				cacheWriteInputTokens: 0,
				outputTokens: 0,
				reasoningOutputTokens: 0,
			},
			last: {
				totalTokens: 1,
				inputTokens: 1,
				cachedInputTokens: 0,
				cacheWriteInputTokens: 0,
				outputTokens: 0,
				reasoningOutputTokens: 0,
			},
			modelContextWindow: null,
		},
	},
	"turn/started": { ...baseThreadNotification, turn: turnFixture },
	"turn/completed": { ...baseThreadNotification, turn: turnFixture },
	"turn/diff/updated": { ...baseThreadNotification, turnId: "turn-1", diff: "" },
	"turn/plan/updated": { ...baseThreadNotification, turnId: "turn-1", explanation: null, plan: [] },
	"item/started": {
		item: threadItemFixture,
		...baseThreadNotification,
		turnId: "turn-1",
		startedAtMs: 1000,
	},
	"item/completed": {
		item: threadItemFixture,
		...baseThreadNotification,
		turnId: "turn-1",
		completedAtMs: 1000,
	},
	"item/agentMessage/delta": baseTurnDelta,
	"item/plan/delta": baseTurnDelta,
	"item/commandExecution/outputDelta": baseTurnDelta,
	"item/commandExecution/terminalInteraction": {
		...baseThreadNotification,
		turnId: "turn-1",
		itemId: "item-1",
		processId: "process-1",
		stdin: "",
	},
	"item/fileChange/outputDelta": baseTurnDelta,
	"item/fileChange/patchUpdated": {
		...baseThreadNotification,
		turnId: "turn-1",
		itemId: "item-1",
		changes: [],
	},
	"serverRequest/resolved": { ...baseThreadNotification, requestId: 1 },
	"item/mcpToolCall/progress": {
		...baseThreadNotification,
		turnId: "turn-1",
		itemId: "item-1",
		message: "progress",
	},
	"account/updated": { authMode: "chatgpt", planType: "pro" },
	"account/rateLimits/updated": {
		rateLimits: {
			limitId: null,
			limitName: null,
			primary: null,
			secondary: null,
			credits: null,
			individualLimit: null,
			spendControlReached: null,
			planType: null,
			rateLimitReachedType: null,
		},
	},
	"fs/changed": { watchId: "watch-1", changedPaths: [] },
	"item/reasoning/summaryTextDelta": { ...baseTurnDelta, summaryIndex: 0 },
	"item/reasoning/summaryPartAdded": {
		...baseThreadNotification,
		turnId: "turn-1",
		itemId: "item-1",
		summaryIndex: 0,
	},
	"item/reasoning/textDelta": { ...baseTurnDelta, contentIndex: 0 },
	"thread/compacted": { ...baseThreadNotification, turnId: "turn-1" },
	"model/rerouted": {
		...baseThreadNotification,
		turnId: "turn-1",
		fromModel: "a",
		toModel: "b",
		reason: "highRiskCyberActivity",
	},
	"model/verification": {
		...baseThreadNotification,
		turnId: "turn-1",
		verifications: ["trustedAccessForCyber"],
	},
	"turn/moderationMetadata": { ...baseThreadNotification, turnId: "turn-1", metadata: {} },
	"model/safetyBuffering/updated": {
		...baseThreadNotification,
		turnId: "turn-1",
		model: "a",
		useCases: [],
		reasons: [],
		showBufferingUi: false,
		fasterModel: null,
	},
	warning: { ...baseThreadNotification, message: "warning" },
	guardianWarning: { ...baseThreadNotification, message: "warning" },
	deprecationNotice: { summary: "deprecated", details: null },
	configWarning: { summary: "warning", details: null },
	"thread/realtime/started": {
		...baseThreadNotification,
		realtimeSessionId: "realtime-1",
		version: "v3",
	},
	"thread/realtime/itemAdded": { ...baseThreadNotification, item: { type: "response.created" } },
	"thread/realtime/item/started": {
		...baseThreadNotification,
		item: {
			id: "realtime-item-1",
			realtimeSessionId: "realtime-1",
			type: "realtimeSessionStarted",
		},
	},
	"thread/realtime/item/transcript/delta": {
		...baseThreadNotification,
		itemId: "realtime-item-1",
		delta: "raw",
	},
	"thread/realtime/item/completed": {
		...baseThreadNotification,
		item: {
			id: "realtime-item-1",
			realtimeSessionId: "realtime-1",
			type: "transcriptSegment",
			role: "user",
			text: "raw",
		},
	},
	"thread/realtime/transcript/delta": { ...baseThreadNotification, role: "user", delta: "raw" },
	"thread/realtime/transcript/done": { ...baseThreadNotification, role: "user", text: "raw" },
	"thread/realtime/outputAudio/delta": {
		...baseThreadNotification,
		audio: { data: "AA==", sampleRate: 24000, numChannels: 1, samplesPerChannel: 1, itemId: null },
	},
	"thread/realtime/sdp": { ...baseThreadNotification, sdp: "v=0" },
	"thread/realtime/error": { ...baseThreadNotification, message: "error" },
	"thread/realtime/closed": { ...baseThreadNotification, reason: null },
	"account/login/completed": {
		success: true,
		error: null,
		loginId: null,
		onboardingEntrypoint: null,
	},
};

export function notificationFixture(method: ServerNotificationMethod): unknown {
	return serverNotificationFixtures[method] ?? {};
}

export const clientNotificationFixtures: Record<ClientNotificationMethod, unknown> = {
	initialized: { method: "initialized" },
};
