import type { ClientNotificationMethod, ResponseMethod, ServerRequestMethod } from "../index.js";

export const threadItemFixture = {
	type: "userMessage",
	id: "item-1",
	clientId: null,
	content: [{ type: "text", text: "hello", text_elements: [] }],
};

export const turnFixture = {
	id: "turn-1",
	items: [threadItemFixture],
	itemsView: "full",
	status: "completed",
	error: null,
	startedAt: 1,
	completedAt: 2,
	durationMs: 1,
};

export const threadFixture = {
	id: "thread-1",
	extra: {},
	sessionId: "session-1",
	forkedFromId: null,
	parentThreadId: null,
	preview: "hello",
	ephemeral: false,
	section: null,
	sectionEnteredAt: null,
	projectId: null,
	historyMode: "paginated",
	modelProvider: "openai",
	createdAt: 1,
	updatedAt: 2,
	recencyAt: null,
	status: { type: "idle" },
	path: null,
	cwd: "/tmp/archboard",
	cliVersion: "0.151.0",
	source: "appServer",
	canAcceptDirectInput: true,
	threadSource: "archboard",
	agentNickname: null,
	agentRole: null,
	gitInfo: null,
	name: null,
	turns: [turnFixture],
};

export const configFixture = {
	model: null,
	review_model: null,
	model_context_window: null,
	model_auto_compact_token_limit: null,
	model_auto_compact_token_limit_scope: null,
	model_provider: null,
	approval_policy: null,
	approvals_reviewer: null,
	sandbox_mode: null,
	sandbox_workspace_write: null,
	forced_chatgpt_workspace_id: null,
	forced_login_method: null,
	web_search: null,
	tools: null,
	instructions: null,
	developer_instructions: null,
	compact_prompt: null,
	model_reasoning_effort: null,
	model_reasoning_summary: null,
	model_verbosity: null,
	service_tier: null,
	analytics: null,
	apps: null,
	browser_use: null,
	computer_use: null,
	desktop: null,
};

export const modelFixture = {
	id: "gpt-5.6-luna",
	model: "gpt-5.6-luna",
	upgrade: null,
	upgradeInfo: null,
	availabilityNux: null,
	displayName: "Luna",
	description: "fixture",
	modelSpecialty: null,
	hidden: false,
	supportedReasoningEfforts: [{ reasoningEffort: "medium", description: "fixture" }],
	defaultReasoningEffort: "medium",
	inputModalities: ["text"],
	supportsPersonality: false,
	multiAgentVersion: null,
	additionalSpeedTiers: [],
	serviceTiers: [],
	defaultServiceTier: null,
	isDefault: true,
};

export const queuedSubmissionFixture = {
	id: "queue-1",
	input: [{ type: "text", text: "queued", text_elements: [] }],
	clientUserMessageId: "client-queue-1",
};

const threadStartResponseFixture = {
	thread: threadFixture,
	model: "gpt-5.6-luna",
	modelProvider: "openai",
	serviceTier: null,
	cwd: "/tmp/archboard",
	runtimeWorkspaceRoots: ["/tmp/archboard"],
	instructionSources: [],
	approvalPolicy: "never",
	approvalsReviewer: "user",
	sandbox: { type: "dangerFullAccess" },
	activePermissionProfile: null,
	reasoningEffort: "medium",
	multiAgentMode: "explicitRequestOnly",
};

export const responseFixtures: Record<ResponseMethod, unknown> = {
	initialize: {
		userAgent: "Codex Desktop/0.151.0",
		codexHome: "/tmp/codex",
		platformFamily: "unix",
		platformOs: "linux",
	},
	"config/read": { config: configFixture, origins: {}, layers: null },
	"configRequirements/read": { requirements: null },
	"account/read": {
		account: { type: "chatgpt", email: null, planType: "pro" },
		requiresOpenaiAuth: true,
	},
	"account/login/start": {
		type: "chatgpt",
		loginId: "login-1",
		authUrl: "https://example.test/login",
	},
	"account/login/cancel": { status: "canceled" },
	"account/logout": {},
	"model/list": { data: [modelFixture], nextCursor: null },
	"thread/start": threadStartResponseFixture,
	"thread/fork": threadStartResponseFixture,
	"thread/list": { data: [threadFixture], nextCursor: null, backwardsCursor: null },
	"thread/loaded/list": { data: ["thread-1"], nextCursor: null },
	"thread/read": { thread: threadFixture },
	"thread/turns/list": { data: [turnFixture], nextCursor: null, backwardsCursor: null },
	"thread/items/list": {
		data: [{ turnId: "turn-1", item: threadItemFixture }],
		nextCursor: null,
		backwardsCursor: null,
	},
	"thread/delete": {},
	"thread/settings/update": {},
	"turn/start": { turn: turnFixture },
	"turn/steer": { turnId: "turn-1" },
	"turn/interrupt": {},
	"thread/queue/add": { queuedSubmission: queuedSubmissionFixture },
	"thread/queue/list": { data: [queuedSubmissionFixture], nextCursor: null },
	"thread/queue/update": { queuedSubmission: queuedSubmissionFixture },
	"thread/queue/delete": { deleted: true },
	"thread/queue/reorder": {},
	"thread/queue/start": { turn: turnFixture },
	"thread/inject_items": {},
	"thread/realtime/start": {},
	"thread/realtime/appendText": {},
	"thread/realtime/appendSpeech": {},
	"thread/realtime/stop": {},
	"thread/timeline/list": {
		data: [{ type: "turnStarted", position: 1, turnId: "turn-1", startedAt: 1 }],
		nextCursor: null,
		activeRealtimeSessionAtPageStart: null,
	},
	"currentTime/read": { currentTimeAt: 1 },
};

export const serverRequestFixtures: Record<ServerRequestMethod, unknown> = {
	"item/commandExecution/requestApproval": {
		kind: "command",
		threadId: "thread-1",
		turnId: "turn-1",
		itemId: "item-1",
		startedAtMs: 1000,
		environmentId: null,
	},
	"item/fileChange/requestApproval": {
		threadId: "thread-1",
		turnId: "turn-1",
		itemId: "item-1",
		startedAtMs: 1000,
	},
	"item/tool/requestUserInput": {
		threadId: "thread-1",
		turnId: "turn-1",
		itemId: "item-1",
		questions: [],
		isBlocking: true,
		autoResolutionMs: null,
	},
	"mcpServer/elicitation/request": {
		threadId: "thread-1",
		turnId: null,
		serverName: "fixture",
		mode: "form",
		_meta: null,
		message: "fixture",
		requestedSchema: { type: "object", properties: {} },
	},
	"item/permissions/requestApproval": {
		threadId: "thread-1",
		turnId: "turn-1",
		itemId: "item-1",
		environmentId: null,
		startedAtMs: 1000,
		cwd: "/tmp/archboard",
		reason: null,
		permissions: { network: null, fileSystem: null },
	},
	"item/tool/call": {
		threadId: "thread-1",
		turnId: "turn-1",
		callId: "call-1",
		namespace: "archboard_app",
		tool: "inspect",
		arguments: { board: "fixture" },
	},
	"account/chatgptAuthTokens/refresh": { reason: "unauthorized", previousAccountId: null },
	"attestation/generate": {},
	"currentTime/read": { threadId: "thread-1" },
	applyPatchApproval: {
		conversationId: "thread-1",
		callId: "call-1",
		fileChanges: { "/tmp/archboard/file": { type: "add", content: "fixture" } },
		reason: null,
		grantRoot: null,
	},
	execCommandApproval: {
		conversationId: "thread-1",
		callId: "call-1",
		approvalId: null,
		command: ["true"],
		cwd: "/tmp/archboard",
		reason: null,
		parsedCmd: [],
	},
};

export const clientNotificationFixtures: Record<ClientNotificationMethod, unknown> = {
	initialized: { method: "initialized" },
};
