import type { ServerNotificationMethod } from "../index.js";
import { threadFixture, threadItemFixture, turnFixture } from "./fixtures.js";

const baseThreadNotification = { threadId: "thread-1" };
const baseTurnDelta = { threadId: "thread-1", turnId: "turn-1", itemId: "item-1", delta: "delta" };

const hookRunFixture = {
	id: "hook-1",
	eventName: "preToolUse",
	handlerType: "command",
	executionMode: "sync",
	scope: "turn",
	sourcePath: "/tmp/archboard/hook.sh",
	source: "project",
	displayOrder: 0,
	status: "completed",
	statusMessage: null,
	startedAt: 1,
	completedAt: 2,
	durationMs: 1,
	entries: [],
};

const guardianActionFixture = {
	type: "command",
	source: "shell",
	command: "true",
	cwd: "/tmp/archboard",
};
const guardianReviewFixture = {
	status: "approved",
	riskLevel: "low",
	userAuthorization: "high",
	rationale: null,
};
const autoReviewBaseFixture = {
	threadId: "thread-1",
	turnId: "turn-1",
	startedAtMs: 1000,
	reviewId: "review-1",
	targetItemId: "item-1",
	review: guardianReviewFixture,
	action: guardianActionFixture,
};

const appFixture = {
	id: "app-1",
	name: "Fixture App",
	description: null,
	logoUrl: null,
	logoUrlDark: null,
	iconAssets: null,
	iconDarkAssets: null,
	distributionChannel: null,
	branding: null,
	appMetadata: null,
	labels: null,
	installUrl: null,
	isAccessible: true,
	isEnabled: true,
	pluginDisplayNames: [],
};

const externalImportFixture = {
	importId: "import-1",
	itemTypeResults: [],
};

export const serverNotificationFixtures: Record<ServerNotificationMethod, unknown> = {
	error: {
		error: {
			message: "fixture",
			codexErrorInfo: null,
			additionalDetails: null,
			misalignment: null,
		},
		willRetry: false,
		...baseThreadNotification,
		turnId: "turn-1",
	},
	"thread/started": { thread: threadFixture },
	"thread/status/changed": { ...baseThreadNotification, status: { type: "idle" } },
	"thread/archived": baseThreadNotification,
	"thread/deleted": baseThreadNotification,
	"thread/unarchived": baseThreadNotification,
	"thread/closed": baseThreadNotification,
	"thread/reverted": baseThreadNotification,
	"skills/changed": {},
	"thread/name/updated": { ...baseThreadNotification, threadName: "Fixture" },
	"thread/goal/updated": {
		...baseThreadNotification,
		turnId: null,
		goal: {
			threadId: "thread-1",
			objective: "fixture",
			status: "active",
			tokenBudget: null,
			tokensUsed: 0,
			timeUsedSeconds: 0,
			createdAt: 1,
			updatedAt: 1,
		},
	},
	"thread/goal/cleared": baseThreadNotification,
	"thread/queue/changed": baseThreadNotification,
	"project/changed": { projectId: "project-1", changeType: "updated" },
	"thread/project/updated": { ...baseThreadNotification, projectId: null },
	"thread/environment/connected": { ...baseThreadNotification, environmentId: "env-1" },
	"thread/environment/disconnected": { ...baseThreadNotification, environmentId: "env-1" },
	"thread/settings/updated": {
		...baseThreadNotification,
		threadSettings: {
			cwd: "/tmp/archboard",
			approvalPolicy: "never",
			approvalsReviewer: "user",
			sandboxPolicy: { type: "dangerFullAccess" },
			activePermissionProfile: null,
			model: "gpt-5.6-luna",
			modelProvider: "openai",
			serviceTier: null,
			effort: "medium",
			summary: "auto",
			collaborationMode: {
				mode: "default",
				settings: {
					model: "gpt-5.6-luna",
					reasoning_effort: "medium",
					developer_instructions: null,
				},
			},
			multiAgentMode: "explicitRequestOnly",
			personality: null,
		},
	},
	"thread/tokenUsage/updated": {
		...baseThreadNotification,
		turnId: "turn-1",
		tokenUsage: {
			total: {
				totalTokens: 1,
				inputTokens: 1,
				cachedInputTokens: 0,
				cacheWriteInputTokens: 0,
				outputTokens: 0,
				reasoningOutputTokens: 0,
			},
			last: {
				totalTokens: 1,
				inputTokens: 1,
				cachedInputTokens: 0,
				cacheWriteInputTokens: 0,
				outputTokens: 0,
				reasoningOutputTokens: 0,
			},
			modelContextWindow: null,
		},
	},
	"turn/started": { ...baseThreadNotification, turn: turnFixture },
	"hook/started": { ...baseThreadNotification, turnId: null, run: hookRunFixture },
	"turn/completed": { ...baseThreadNotification, turn: turnFixture },
	"hook/completed": { ...baseThreadNotification, turnId: null, run: hookRunFixture },
	"turn/diff/updated": { ...baseThreadNotification, turnId: "turn-1", diff: "" },
	"turn/plan/updated": { ...baseThreadNotification, turnId: "turn-1", explanation: null, plan: [] },
	"item/started": {
		item: threadItemFixture,
		...baseThreadNotification,
		turnId: "turn-1",
		startedAtMs: 1000,
	},
	"item/autoApprovalReview/started": autoReviewBaseFixture,
	"item/autoApprovalReview/completed": {
		...autoReviewBaseFixture,
		completedAtMs: 1100,
		decisionSource: "agent",
	},
	"autoApprovalReview/strictReviewRequired": {
		...baseThreadNotification,
		turnId: "turn-1",
		startedAtMs: 1000,
	},
	"item/completed": {
		item: threadItemFixture,
		...baseThreadNotification,
		turnId: "turn-1",
		completedAtMs: 1000,
	},
	"rawResponseItem/completed": {
		...baseThreadNotification,
		turnId: "turn-1",
		item: { type: "message", role: "assistant", content: [{ type: "output_text", text: "raw" }] },
	},
	"rawResponse/completed": {
		...baseThreadNotification,
		turnId: "turn-1",
		responseId: "response-1",
		usage: null,
		usageMetadata: null,
	},
	"item/agentMessage/delta": baseTurnDelta,
	"item/plan/delta": baseTurnDelta,
	"command/exec/outputDelta": {
		processId: "process-1",
		stream: "stdout",
		deltaBase64: "AA==",
		capReached: false,
	},
	"process/outputDelta": {
		processHandle: "process-1",
		stream: "stderr",
		deltaBase64: "AA==",
		capReached: false,
	},
	"process/exited": {
		processHandle: "process-1",
		exitCode: 0,
		stdout: "",
		stdoutCapReached: false,
		stderr: "",
		stderrCapReached: false,
	},
	"item/commandExecution/outputDelta": baseTurnDelta,
	"item/commandExecution/terminalInteraction": {
		...baseThreadNotification,
		turnId: "turn-1",
		itemId: "item-1",
		processId: "process-1",
		stdin: "",
	},
	"item/fileChange/outputDelta": baseTurnDelta,
	"item/fileChange/patchUpdated": {
		...baseThreadNotification,
		turnId: "turn-1",
		itemId: "item-1",
		changes: [],
	},
	"serverRequest/resolved": { ...baseThreadNotification, requestId: 1 },
	"item/mcpToolCall/progress": {
		...baseThreadNotification,
		turnId: "turn-1",
		itemId: "item-1",
		message: "progress",
	},
	"mcpServer/oauthLogin/completed": {
		name: "fixture",
		threadId: null,
		success: true,
	},
	"mcpServer/startupStatus/updated": {
		threadId: null,
		name: "fixture",
		status: "ready",
		error: null,
		failureReason: null,
	},
	"mcpServer/event/stream/notification": {
		subscriptionId: "subscription-1",
		notification: { method: "notifications/progress", params: {} },
	},
	"account/updated": { authMode: "chatgpt", planType: "pro" },
	"account/rateLimits/updated": {
		rateLimits: {
			limitId: null,
			limitName: null,
			primary: null,
			secondary: null,
			credits: null,
			individualLimit: null,
			spendControlReached: null,
			planType: null,
			rateLimitReachedType: null,
		},
	},
	"app/list/updated": { data: [appFixture] },
	"remoteControl/status/changed": {
		status: "connected",
		serverName: "fixture",
		installationId: "installation-1",
		environmentId: null,
	},
	"externalAgentConfig/import/progress": externalImportFixture,
	"externalAgentConfig/import/completed": externalImportFixture,
	"fs/changed": { watchId: "watch-1", changedPaths: [] },
	"item/reasoning/summaryTextDelta": { ...baseTurnDelta, summaryIndex: 0 },
	"item/reasoning/summaryPartAdded": {
		...baseThreadNotification,
		turnId: "turn-1",
		itemId: "item-1",
		summaryIndex: 0,
	},
	"item/reasoning/textDelta": { ...baseTurnDelta, contentIndex: 0 },
	"thread/compacted": { ...baseThreadNotification, turnId: "turn-1" },
	"model/rerouted": {
		...baseThreadNotification,
		turnId: "turn-1",
		fromModel: "a",
		toModel: "b",
		reason: "highRiskCyberActivity",
	},
	"model/verification": {
		...baseThreadNotification,
		turnId: "turn-1",
		verifications: ["trustedAccessForCyber"],
	},
	"turn/moderationMetadata": { ...baseThreadNotification, turnId: "turn-1", metadata: {} },
	"model/safetyBuffering/updated": {
		...baseThreadNotification,
		turnId: "turn-1",
		model: "a",
		useCases: [],
		reasons: [],
		showBufferingUi: false,
		fasterModel: null,
	},
	warning: { ...baseThreadNotification, message: "warning" },
	guardianWarning: { ...baseThreadNotification, message: "warning" },
	deprecationNotice: { summary: "deprecated", details: null },
	configWarning: { summary: "warning", details: null },
	"fuzzyFileSearch/sessionUpdated": {
		sessionId: "search-1",
		query: "fixture",
		files: [],
	},
	"fuzzyFileSearch/sessionCompleted": { sessionId: "search-1" },
	"thread/realtime/started": {
		...baseThreadNotification,
		realtimeSessionId: "realtime-1",
		version: "v3",
	},
	"thread/realtime/itemAdded": { ...baseThreadNotification, item: { type: "response.created" } },
	"thread/realtime/item/started": {
		...baseThreadNotification,
		item: {
			id: "realtime-item-1",
			realtimeSessionId: "realtime-1",
			type: "realtimeSessionStarted",
		},
	},
	"thread/realtime/item/transcript/delta": {
		...baseThreadNotification,
		itemId: "realtime-item-1",
		delta: "raw",
	},
	"thread/realtime/item/completed": {
		...baseThreadNotification,
		item: {
			id: "realtime-item-1",
			realtimeSessionId: "realtime-1",
			type: "transcriptSegment",
			role: "user",
			text: "raw",
		},
	},
	"thread/realtime/transcript/delta": { ...baseThreadNotification, role: "user", delta: "raw" },
	"thread/realtime/transcript/done": { ...baseThreadNotification, role: "user", text: "raw" },
	"thread/realtime/outputAudio/delta": {
		...baseThreadNotification,
		audio: { data: "AA==", sampleRate: 24000, numChannels: 1, samplesPerChannel: 1, itemId: null },
	},
	"thread/realtime/sdp": { ...baseThreadNotification, sdp: "v=0" },
	"thread/realtime/error": { ...baseThreadNotification, message: "error" },
	"thread/realtime/closed": { ...baseThreadNotification, reason: null },
	"windows/worldWritableWarning": { samplePaths: [], extraCount: 0, failedScan: false },
	"windowsSandbox/setupCompleted": { mode: "unelevated", success: true, error: null },
	"account/login/completed": {
		success: true,
		error: null,
		loginId: null,
		onboardingEntrypoint: null,
	},
};

export function notificationFixture(method: ServerNotificationMethod): unknown {
	return serverNotificationFixtures[method];
}
