import type { NotificationUnionChallenge, PathSegment } from "./union-challenge-utils.js";
import { future, replace } from "./union-challenge-utils.js";

export function threadItemChallenges(...path: PathSegment[]): NotificationUnionChallenge[] {
	return [
		future("thread-item.type", ...path, "type"),
		future("thread-item.input.type", ...path, "content", 0, "type"),
		replace("thread-item.input.image.detail", path, {
			type: "userMessage",
			id: "item-1",
			clientId: null,
			content: [{ type: "image", detail: "futureUnionMember", url: "https://example.test" }],
		}),
		replace("thread-item.agentMessage.phase", path, {
			type: "agentMessage",
			id: "item-1",
			text: "fixture",
			phase: "futureUnionMember",
			memoryCitation: null,
			delivery: null,
		}),
		replace("thread-item.agentMessage.delivery", path, {
			type: "agentMessage",
			id: "item-1",
			text: "fixture",
			phase: null,
			memoryCitation: null,
			delivery: "futureUnionMember",
		}),
		replace("thread-item.functionCallOutput.content.type", path, {
			type: "functionCallOutput",
			id: "item-1",
			name: "fixture",
			namespace: null,
			output: [{ type: "futureUnionMember", text: "fixture" }],
		}),
		replace("thread-item.commandExecution.source", path, {
			type: "commandExecution",
			id: "item-1",
			pluginId: null,
			scriptPath: null,
			command: "true",
			cwd: "/tmp/archboard",
			processId: null,
			source: "futureUnionMember",
			status: "completed",
			commandActions: [],
			aggregatedOutput: null,
			exitCode: 0,
			durationMs: 1,
		}),
		replace("thread-item.commandExecution.status", path, {
			type: "commandExecution",
			id: "item-1",
			pluginId: null,
			scriptPath: null,
			command: "true",
			cwd: "/tmp/archboard",
			processId: null,
			source: "agent",
			status: "futureUnionMember",
			commandActions: [],
			aggregatedOutput: null,
			exitCode: 0,
			durationMs: 1,
		}),
		replace("thread-item.commandExecution.commandActions.type", path, {
			type: "commandExecution",
			id: "item-1",
			pluginId: null,
			scriptPath: null,
			command: "true",
			cwd: "/tmp/archboard",
			processId: null,
			source: "agent",
			status: "completed",
			commandActions: [{ type: "futureUnionMember", command: "true" }],
			aggregatedOutput: null,
			exitCode: 0,
			durationMs: 1,
		}),
		replace("thread-item.fileChange.status", path, {
			type: "fileChange",
			id: "item-1",
			changes: [],
			status: "futureUnionMember",
		}),
		replace("thread-item.fileChange.kind.type", path, {
			type: "fileChange",
			id: "item-1",
			changes: [{ path: "file", kind: { type: "futureUnionMember" }, diff: "" }],
			status: "completed",
		}),
		replace("thread-item.mcpToolCall.status", path, {
			type: "mcpToolCall",
			id: "item-1",
			server: "fixture",
			tool: "fixture",
			status: "futureUnionMember",
			arguments: {},
			appContext: null,
			pluginId: null,
			readOnlyHint: null,
			result: null,
			error: null,
			durationMs: 1,
		}),
		replace("thread-item.dynamicToolCall.status", path, {
			type: "dynamicToolCall",
			id: "item-1",
			namespace: null,
			tool: "fixture",
			arguments: {},
			status: "futureUnionMember",
			contentItems: null,
			success: null,
			durationMs: 1,
		}),
		replace("thread-item.dynamicToolCall.contentItems.type", path, {
			type: "dynamicToolCall",
			id: "item-1",
			namespace: null,
			tool: "fixture",
			arguments: {},
			status: "completed",
			contentItems: [{ type: "futureUnionMember", text: "fixture" }],
			success: true,
			durationMs: 1,
		}),
		replace("thread-item.collabAgentToolCall.tool", path, {
			type: "collabAgentToolCall",
			id: "item-1",
			tool: "futureUnionMember",
			status: "completed",
			senderThreadId: "thread-1",
			receiverThreadIds: [],
			prompt: null,
			model: null,
			reasoningEffort: null,
			agentsStates: {},
		}),
		replace("thread-item.collabAgentToolCall.status", path, {
			type: "collabAgentToolCall",
			id: "item-1",
			tool: "wait",
			status: "futureUnionMember",
			senderThreadId: "thread-1",
			receiverThreadIds: [],
			prompt: null,
			model: null,
			reasoningEffort: null,
			agentsStates: {},
		}),
		replace("thread-item.collabAgentToolCall.agentState.status", path, {
			type: "collabAgentToolCall",
			id: "item-1",
			tool: "wait",
			status: "completed",
			senderThreadId: "thread-1",
			receiverThreadIds: [],
			prompt: null,
			model: null,
			reasoningEffort: null,
			agentsStates: { "agent-1": { status: "futureUnionMember", message: null } },
		}),
		replace("thread-item.subAgentActivity.kind", path, {
			type: "subAgentActivity",
			id: "item-1",
			kind: "futureUnionMember",
			agentThreadId: "thread-1",
			agentPath: "1",
		}),
		replace("thread-item.webSearch.action.type", path, {
			type: "webSearch",
			id: "item-1",
			query: "fixture",
			action: { type: "futureUnionMember" },
			results: null,
		}),
	];
}
