import type { ServerNotificationMethod } from "../index.js";
import type { NotificationUnionChallenge } from "./union-challenge-utils.js";
import { generated } from "./union-challenge-utils.js";

function generatedCases(...names: readonly string[]): NotificationUnionChallenge[] {
	return names.map((name) => generated(name));
}

/**
 * Independently authored named challenges for every closed-union path in the
 * generated notification graph. Keep this inventory separate from production
 * conformance metadata: the protocol test compares the two for exact
 * equality.
 */
export const SERVER_NOTIFICATION_UNION_CHALLENGES = {
	error: generatedCases(
		"error.codexErrorInfo",
		"error.codexErrorInfo.activeTurnNotSteerable.turnKind",
		"error.misalignment",
		"error.misalignment.steer",
	),
	"thread/started": generatedCases(
		"thread.gitInfo",
		"thread.historyMode",
		"thread.section",
		"thread.section.appearance",
		"thread.source",
		"thread.source.subAgent",
		"thread.status.active.activeFlags",
		"thread.status.type",
		"thread.turns.error",
		"thread.turns.error.codexErrorInfo",
		"thread.turns.error.codexErrorInfo.activeTurnNotSteerable.turnKind",
		"thread.turns.error.misalignment",
		"thread.turns.error.misalignment.steer",
		"thread.turns.items.agentMessage.delivery",
		"thread.turns.items.agentMessage.memoryCitation",
		"thread.turns.items.agentMessage.phase",
		"thread.turns.items.collabAgentToolCall.agentsStates.status",
		"thread.turns.items.collabAgentToolCall.status",
		"thread.turns.items.collabAgentToolCall.tool",
		"thread.turns.items.commandExecution.commandActions.type",
		"thread.turns.items.commandExecution.source",
		"thread.turns.items.commandExecution.status",
		"thread.turns.items.dynamicToolCall.contentItems.type",
		"thread.turns.items.dynamicToolCall.status",
		"thread.turns.items.fileChange.changes.kind.type",
		"thread.turns.items.fileChange.status",
		"thread.turns.items.functionCallOutput.output",
		"thread.turns.items.functionCallOutput.output.input_image.detail",
		"thread.turns.items.functionCallOutput.output.type",
		"thread.turns.items.imageGeneration.failure.type",
		"thread.turns.items.mcpToolCall.appContext",
		"thread.turns.items.mcpToolCall.error",
		"thread.turns.items.mcpToolCall.result",
		"thread.turns.items.mcpToolCall.status",
		"thread.turns.items.subAgentActivity.kind",
		"thread.turns.items.type",
		"thread.turns.items.userMessage.content.image.detail",
		"thread.turns.items.userMessage.content.localImage.detail",
		"thread.turns.items.userMessage.content.type",
		"thread.turns.items.webSearch.action.type",
		"thread.turns.itemsView",
		"thread.turns.status",
	),
	"thread/status/changed": generatedCases("status.active.activeFlags", "status.type"),
	"thread/archived": [],
	"thread/deleted": [],
	"thread/unarchived": [],
	"thread/closed": [],
	"thread/reverted": [],
	"skills/changed": [],
	"thread/name/updated": [],
	"thread/goal/updated": generatedCases("goal.status"),
	"thread/goal/cleared": [],
	"thread/queue/changed": [],
	"project/changed": generatedCases("changeType"),
	"thread/project/updated": [],
	"thread/environment/connected": [],
	"thread/environment/disconnected": [],
	"thread/settings/updated": generatedCases(
		"threadSettings.activePermissionProfile",
		"threadSettings.approvalPolicy",
		"threadSettings.approvalsReviewer",
		"threadSettings.collaborationMode.mode",
		"threadSettings.multiAgentMode",
		"threadSettings.personality",
		"threadSettings.sandboxPolicy.externalSandbox.networkAccess",
		"threadSettings.sandboxPolicy.type",
		"threadSettings.summary",
	),
	"thread/tokenUsage/updated": [],
	"turn/started": generatedCases(
		"turn.error",
		"turn.error.codexErrorInfo",
		"turn.error.codexErrorInfo.activeTurnNotSteerable.turnKind",
		"turn.error.misalignment",
		"turn.error.misalignment.steer",
		"turn.items.agentMessage.delivery",
		"turn.items.agentMessage.memoryCitation",
		"turn.items.agentMessage.phase",
		"turn.items.collabAgentToolCall.agentsStates.status",
		"turn.items.collabAgentToolCall.status",
		"turn.items.collabAgentToolCall.tool",
		"turn.items.commandExecution.commandActions.type",
		"turn.items.commandExecution.source",
		"turn.items.commandExecution.status",
		"turn.items.dynamicToolCall.contentItems.type",
		"turn.items.dynamicToolCall.status",
		"turn.items.fileChange.changes.kind.type",
		"turn.items.fileChange.status",
		"turn.items.functionCallOutput.output",
		"turn.items.functionCallOutput.output.input_image.detail",
		"turn.items.functionCallOutput.output.type",
		"turn.items.imageGeneration.failure.type",
		"turn.items.mcpToolCall.appContext",
		"turn.items.mcpToolCall.error",
		"turn.items.mcpToolCall.result",
		"turn.items.mcpToolCall.status",
		"turn.items.subAgentActivity.kind",
		"turn.items.type",
		"turn.items.userMessage.content.image.detail",
		"turn.items.userMessage.content.localImage.detail",
		"turn.items.userMessage.content.type",
		"turn.items.webSearch.action.type",
		"turn.itemsView",
		"turn.status",
	),
	"hook/started": generatedCases(
		"run.entries.kind",
		"run.eventName",
		"run.executionMode",
		"run.handlerType",
		"run.scope",
		"run.source",
		"run.status",
	),
	"turn/completed": generatedCases(
		"turn.error",
		"turn.error.codexErrorInfo",
		"turn.error.codexErrorInfo.activeTurnNotSteerable.turnKind",
		"turn.error.misalignment",
		"turn.error.misalignment.steer",
		"turn.items.agentMessage.delivery",
		"turn.items.agentMessage.memoryCitation",
		"turn.items.agentMessage.phase",
		"turn.items.collabAgentToolCall.agentsStates.status",
		"turn.items.collabAgentToolCall.status",
		"turn.items.collabAgentToolCall.tool",
		"turn.items.commandExecution.commandActions.type",
		"turn.items.commandExecution.source",
		"turn.items.commandExecution.status",
		"turn.items.dynamicToolCall.contentItems.type",
		"turn.items.dynamicToolCall.status",
		"turn.items.fileChange.changes.kind.type",
		"turn.items.fileChange.status",
		"turn.items.functionCallOutput.output",
		"turn.items.functionCallOutput.output.input_image.detail",
		"turn.items.functionCallOutput.output.type",
		"turn.items.imageGeneration.failure.type",
		"turn.items.mcpToolCall.appContext",
		"turn.items.mcpToolCall.error",
		"turn.items.mcpToolCall.result",
		"turn.items.mcpToolCall.status",
		"turn.items.subAgentActivity.kind",
		"turn.items.type",
		"turn.items.userMessage.content.image.detail",
		"turn.items.userMessage.content.localImage.detail",
		"turn.items.userMessage.content.type",
		"turn.items.webSearch.action.type",
		"turn.itemsView",
		"turn.status",
	),
	"hook/completed": generatedCases(
		"run.entries.kind",
		"run.eventName",
		"run.executionMode",
		"run.handlerType",
		"run.scope",
		"run.source",
		"run.status",
	),
	"turn/diff/updated": [],
	"turn/plan/updated": generatedCases("plan.status"),
	"item/started": generatedCases(
		"item.agentMessage.delivery",
		"item.agentMessage.memoryCitation",
		"item.agentMessage.phase",
		"item.collabAgentToolCall.agentsStates.status",
		"item.collabAgentToolCall.status",
		"item.collabAgentToolCall.tool",
		"item.commandExecution.commandActions.type",
		"item.commandExecution.source",
		"item.commandExecution.status",
		"item.dynamicToolCall.contentItems.type",
		"item.dynamicToolCall.status",
		"item.fileChange.changes.kind.type",
		"item.fileChange.status",
		"item.functionCallOutput.output",
		"item.functionCallOutput.output.input_image.detail",
		"item.functionCallOutput.output.type",
		"item.imageGeneration.failure.type",
		"item.mcpToolCall.appContext",
		"item.mcpToolCall.error",
		"item.mcpToolCall.result",
		"item.mcpToolCall.status",
		"item.subAgentActivity.kind",
		"item.type",
		"item.userMessage.content.image.detail",
		"item.userMessage.content.localImage.detail",
		"item.userMessage.content.type",
		"item.webSearch.action.type",
	),
	"item/autoApprovalReview/started": generatedCases(
		"action.command.source",
		"action.execve.source",
		"action.networkAccess.protocol",
		"action.requestPermissions.permissions.fileSystem",
		"action.requestPermissions.permissions.fileSystem.entries.access",
		"action.requestPermissions.permissions.fileSystem.entries.path.special.value.kind",
		"action.requestPermissions.permissions.fileSystem.entries.path.type",
		"action.requestPermissions.permissions.network",
		"action.type",
		"review.riskLevel",
		"review.status",
		"review.userAuthorization",
	),
	"item/autoApprovalReview/completed": generatedCases(
		"action.command.source",
		"action.execve.source",
		"action.networkAccess.protocol",
		"action.requestPermissions.permissions.fileSystem",
		"action.requestPermissions.permissions.fileSystem.entries.access",
		"action.requestPermissions.permissions.fileSystem.entries.path.special.value.kind",
		"action.requestPermissions.permissions.fileSystem.entries.path.type",
		"action.requestPermissions.permissions.network",
		"action.type",
		"decisionSource",
		"review.riskLevel",
		"review.status",
		"review.userAuthorization",
	),
	"autoApprovalReview/strictReviewRequired": [],
	"item/completed": generatedCases(
		"item.agentMessage.delivery",
		"item.agentMessage.memoryCitation",
		"item.agentMessage.phase",
		"item.collabAgentToolCall.agentsStates.status",
		"item.collabAgentToolCall.status",
		"item.collabAgentToolCall.tool",
		"item.commandExecution.commandActions.type",
		"item.commandExecution.source",
		"item.commandExecution.status",
		"item.dynamicToolCall.contentItems.type",
		"item.dynamicToolCall.status",
		"item.fileChange.changes.kind.type",
		"item.fileChange.status",
		"item.functionCallOutput.output",
		"item.functionCallOutput.output.input_image.detail",
		"item.functionCallOutput.output.type",
		"item.imageGeneration.failure.type",
		"item.mcpToolCall.appContext",
		"item.mcpToolCall.error",
		"item.mcpToolCall.result",
		"item.mcpToolCall.status",
		"item.subAgentActivity.kind",
		"item.type",
		"item.userMessage.content.image.detail",
		"item.userMessage.content.localImage.detail",
		"item.userMessage.content.type",
		"item.webSearch.action.type",
	),
	"rawResponseItem/completed": generatedCases(
		"item.agent_message.content.type",
		"item.custom_tool_call_output.output",
		"item.custom_tool_call_output.output.input_image.detail",
		"item.custom_tool_call_output.output.type",
		"item.function_call_output.output",
		"item.function_call_output.output.input_image.detail",
		"item.function_call_output.output.type",
		"item.local_shell_call.action.env",
		"item.local_shell_call.action.type",
		"item.local_shell_call.status",
		"item.message.content.input_image.detail",
		"item.message.content.type",
		"item.message.phase",
		"item.reasoning.content.type",
		"item.reasoning.summary.type",
		"item.type",
		"item.web_search_call.action.type",
	),
	"rawResponse/completed": generatedCases("usage", "usageMetadata"),
	"item/agentMessage/delta": [],
	"item/plan/delta": [],
	"command/exec/outputDelta": generatedCases("stream"),
	"process/outputDelta": generatedCases("stream"),
	"process/exited": [],
	"item/commandExecution/outputDelta": [],
	"item/commandExecution/terminalInteraction": [],
	"item/fileChange/outputDelta": [],
	"item/fileChange/patchUpdated": generatedCases("changes.kind.type"),
	"serverRequest/resolved": generatedCases("requestId"),
	"item/mcpToolCall/progress": [],
	"mcpServer/oauthLogin/completed": [],
	"mcpServer/startupStatus/updated": generatedCases("failureReason", "status"),
	"mcpServer/event/stream/notification": [],
	"account/updated": generatedCases("authMode", "planType"),
	"account/rateLimits/updated": generatedCases(
		"rateLimits.credits",
		"rateLimits.individualLimit",
		"rateLimits.planType",
		"rateLimits.primary",
		"rateLimits.rateLimitReachedType",
		"rateLimits.secondary",
	),
	"app/list/updated": generatedCases(
		"data.appMetadata",
		"data.appMetadata.review",
		"data.branding",
		"data.iconAssets",
		"data.iconDarkAssets",
		"data.labels",
	),
	"remoteControl/status/changed": generatedCases("status"),
	"externalAgentConfig/import/progress": generatedCases(
		"itemTypeResults.failures.itemType",
		"itemTypeResults.itemType",
		"itemTypeResults.successes.itemType",
	),
	"externalAgentConfig/import/completed": generatedCases(
		"itemTypeResults.failures.itemType",
		"itemTypeResults.itemType",
		"itemTypeResults.successes.itemType",
	),
	"fs/changed": [],
	"item/reasoning/summaryTextDelta": [],
	"item/reasoning/summaryPartAdded": [],
	"item/reasoning/textDelta": [],
	"thread/compacted": [],
	"model/rerouted": generatedCases("reason"),
	"model/verification": generatedCases("verifications"),
	"turn/moderationMetadata": [],
	"model/safetyBuffering/updated": [],
	warning: [],
	guardianWarning: [],
	deprecationNotice: [],
	configWarning: [],
	"fuzzyFileSearch/sessionUpdated": generatedCases("files.match_type"),
	"fuzzyFileSearch/sessionCompleted": [],
	"thread/realtime/started": generatedCases("version"),
	"thread/realtime/itemAdded": [],
	"thread/realtime/item/started": generatedCases(
		"item.bemItemPromoted.presentation.type",
		"item.realtimeSessionClosed.outcome",
		"item.transcriptSegment.role",
		"item.type",
	),
	"thread/realtime/item/transcript/delta": [],
	"thread/realtime/item/completed": generatedCases(
		"item.bemItemPromoted.presentation.type",
		"item.realtimeSessionClosed.outcome",
		"item.transcriptSegment.role",
		"item.type",
	),
	"thread/realtime/transcript/delta": [],
	"thread/realtime/transcript/done": [],
	"thread/realtime/outputAudio/delta": [],
	"thread/realtime/sdp": [],
	"thread/realtime/error": [],
	"thread/realtime/closed": [],
	"windows/worldWritableWarning": [],
	"windowsSandbox/setupCompleted": generatedCases("mode"),
	"account/login/completed": generatedCases("onboardingEntrypoint"),
} as const satisfies Record<ServerNotificationMethod, readonly NotificationUnionChallenge[]>;
