import { describe, expect, test } from "bun:test";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { z } from "zod";
import {
	artifactFailure,
	artifactNames,
	createArtifactFixture,
} from "./support/artifact-fixture.ts";

const proofSchema = z.object({
	schemaVersion: z.literal(6),
	generatedFrom: z.literal("src/cli/commands/run.ts"),
	routes: z.array(
		z
			.object({
				name: z.string(),
				parent: z.string().nullable(),
				handlerOwner: z.string(),
				parserOwner: z.string(),
			})
			.passthrough(),
	),
	contracts: z.array(z.object({ name: z.string() }).passthrough()),
});
const expectedHashes: Readonly<Record<(typeof artifactNames)[number], string>> = {
	"cli-command-audit.md": "2f43d928290d6ef3e65e94989204facdfb71c84b8e4fa5952dd218ee3829555c",
	"command-contract-proof.json": "287c70c8a755773865ac4fecd6a08e51d10aa430b1a0229f8ed85fb3a7eef542",
	"command-contract-proof.md": "5eae34c89b28ed24b9f2291a0394120c5ca0b55812b60424d05bef43b3557f8e",
};
const sha256 = (bytes: Buffer) => createHash("sha256").update(bytes).digest("hex");

function validateArtifacts(directory: string): void {
	for (const name of artifactNames)
		expect(sha256(readFileSync(join(directory, name)))).toBe(expectedHashes[name]);
}

describe("command contract artifact generation", () => {
	test("generates exact typed bytes twice from absent directories", () => {
		const fixture = createArtifactFixture();
		try {
			const statusBefore = fixture.status();
			expect(existsSync(fixture.first)).toBe(false);
			expect(existsSync(fixture.second)).toBe(false);
			const first = fixture.generate(fixture.first);
			const second = fixture.generate(fixture.second);
			expect(first.status, artifactFailure(first)).toBe(0);
			expect(second.status, artifactFailure(second)).toBe(0);
			expect(first.stderr).toContain("bun scripts/generate-cli-contract.mjs");
			expect(second.stderr).toContain("bun scripts/generate-cli-contract.mjs");
			expect(fixture.files(fixture.first)).toEqual(artifactNames.toSorted());
			expect(fixture.files(fixture.second)).toEqual(artifactNames.toSorted());
			for (const name of artifactNames) {
				expect(fixture.bytes(fixture.first, name)).toEqual(fixture.bytes(fixture.second, name));
			}
			validateArtifacts(fixture.first);
			validateArtifacts(fixture.second);
			const proof = proofSchema.parse(
				JSON.parse(fixture.bytes(fixture.first, "command-contract-proof.json").toString()),
			);
			expect(proof.routes.map((route) => route.name)).toEqual(
				proof.contracts.map((contract) => contract.name),
			);
			expect(fixture.status()).toBe(statusBefore);
		} finally {
			fixture.dispose();
		}
	});

	test("reports generated files in the declared write order", () => {
		const fixture = createArtifactFixture();
		try {
			const result = fixture.generate(fixture.first);
			expect(result.status, artifactFailure(result)).toBe(0);
			expect(result.stdout).toBe(
				artifactNames.map((name) => `generated ${join(fixture.first, name)}\n`).join(""),
			);
			for (const name of artifactNames) expect(existsSync(join(fixture.first, name))).toBe(true);
		} finally {
			fixture.dispose();
		}
	});

	test("rejects an incomplete private output request", () => {
		const fixture = createArtifactFixture();
		try {
			const result = fixture.generate("");
			expect(result.status).not.toBe(0);
			expect(result.stdout).toBe("");
			expect(existsSync(fixture.first)).toBe(false);
		} finally {
			fixture.dispose();
		}
	});

	test("detects reordered artifacts and changed generated bytes", () => {
		const fixture = createArtifactFixture();
		try {
			expect(fixture.generate(fixture.first).status).toBe(0);
			const reordered = artifactNames.toReversed();
			expect(reordered).not.toEqual(artifactNames);
			const proofPath = join(fixture.first, "command-contract-proof.json");
			writeFileSync(proofPath, Buffer.concat([readFileSync(proofPath), Buffer.from(" ")]));
			expect(() => validateArtifacts(fixture.first)).toThrow();
		} finally {
			fixture.dispose();
		}
	});
});
