export const EXPECTED_IMPORTS = [
	'@import "tailwindcss/theme.css" layer(theme);',
	'@import "tailwindcss/utilities.css" layer(utilities);',
	'@import "../shell/shell.css";',
] as const;

export const LIGHT_TOKENS = {
	"--arch-font-ui": '"Archboard Onest"',
	"--arch-font-technical": '"Archboard DM Mono"',
	"--arch-weight-regular": "400",
	"--arch-weight-medium": "500",
	"--arch-weight-semibold": "600",
	"--arch-weight-bold": "700",
	"--arch-wordmark-tracking": "-0.02027027027em",
	"--arch-text-kicker-size": "9px",
	"--arch-text-kicker-line": "12px",
	"--arch-text-technical-size": "10px",
	"--arch-text-technical-line": "14px",
	"--arch-text-body-size": "12px",
	"--arch-text-body-line": "16px",
	"--arch-text-control-size": "13px",
	"--arch-text-control-line": "18px",
	"--arch-text-title-size": "14px",
	"--arch-text-title-line": "20px",
	"--arch-text-primary-size": "16px",
	"--arch-text-primary-line": "22px",
	"--arch-color-selection": "#155eef",
	"--arch-color-status": "#a3e635",
	"--arch-color-foreground": "#18181b",
	"--arch-color-muted-foreground": "#5f6269",
	"--arch-color-faint-foreground": "#777b84",
	"--arch-color-border": "#cfd1d4",
	"--arch-color-border-subtle": "#e3e4e6",
	"--arch-color-background": "#f4f4f1",
	"--arch-color-surface": "#fafaf8",
	"--arch-color-surface-raised": "#fff",
	"--arch-color-surface-subtle": "#eeeeeb",
	"--arch-color-surface-hover": "#e7e8e8",
	"--arch-color-primary": "var(--arch-color-selection)",
	"--arch-color-primary-hover": "#0b4dcc",
	"--arch-color-primary-subtle": "#dce7ff",
	"--arch-color-primary-foreground": "#fff",
	"--arch-color-destructive": "#b42318",
	"--arch-color-destructive-subtle": "#fee4e2",
	"--arch-color-warning": "#8a4b08",
	"--arch-color-warning-subtle": "#ffead5",
	"--arch-color-status-foreground": "#315314",
	"--arch-color-status-subtle": "#e7f9b7",
	"--arch-color-offline": "#b42318",
	"--arch-color-path-focus-dim": "rgba(244, 244, 241, 0.78)",
	"--arch-radius-hairline": "1px",
	"--arch-radius-compact": "2px",
	"--arch-radius-control": "3px",
	"--arch-radius-panel": "4px",
	"--arch-radius-dialog": "5px",
	"--arch-radius-round": "50%",
	"--arch-space-rule": "1px",
	"--arch-space-compact": "2px",
	"--arch-space-tight": "4px",
	"--arch-space-control": "8px",
	"--arch-space-control-inline": "12px",
	"--arch-space-region": "16px",
	"--arch-space-panel": "22px",
	"--arch-size-touch-target": "44px",
	"--arch-size-header": "56px",
	"--arch-shadow-flat": "none",
	"--arch-opacity-disabled-control": "0.46",
	"--arch-opacity-disabled-item": "0.5",
	"--arch-opacity-disabled-action": "0.52",
	"--arch-opacity-status-rest": "0.84",
	"--arch-opacity-status-active": "1",
	"--arch-duration-control": "140ms",
	"--arch-duration-status": "2.4s",
	"--arch-ease-control": "ease",
	"--arch-ease-status": "ease-in-out",
	"--arch-status-iteration-count": "infinite",
	"--arch-animation-status":
		"agent-pulse var(--arch-duration-status) var(--arch-ease-status) var(--arch-status-iteration-count)",
} as const;

export const DARK_TOKEN_OVERRIDES = {
	"--arch-color-selection": "#155eef",
	"--arch-color-status": "#a3e635",
	"--arch-color-foreground": "#f4f4f0",
	"--arch-color-muted-foreground": "#b5b7bd",
	"--arch-color-faint-foreground": "#90949e",
	"--arch-color-border": "#3b3e45",
	"--arch-color-border-subtle": "#2d3036",
	"--arch-color-background": "#17181b",
	"--arch-color-surface": "#111216",
	"--arch-color-surface-raised": "#1d1f24",
	"--arch-color-surface-subtle": "#26282e",
	"--arch-color-surface-hover": "#30333a",
	"--arch-color-primary": "var(--arch-color-selection)",
	"--arch-color-primary-hover": "#8eb0ff",
	"--arch-color-primary-subtle": "#1a3267",
	"--arch-color-primary-foreground": "#fff",
	"--arch-color-destructive": "#f97066",
	"--arch-color-destructive-subtle": "#4b2424",
	"--arch-color-warning": "#fdb022",
	"--arch-color-warning-subtle": "#493115",
	"--arch-color-status-foreground": "#d9ff84",
	"--arch-color-status-subtle": "#273716",
	"--arch-color-offline": "#f97066",
	"--arch-color-path-focus-dim": "rgba(17, 18, 22, 0.76)",
} as const;

export const REDUCED_MOTION_OVERRIDES = {
	"--arch-duration-control": "0.001ms",
	"--arch-duration-status": "0.001ms",
	"--arch-status-iteration-count": "1",
} as const;

export const HIGH_CONTRAST_FORBIDDEN_DECLARATIONS = ["forced-color-adjust: none"] as const;

export const SEMANTIC_ALIASES = {
	"--color-background": "var(--arch-color-background)",
	"--color-foreground": "var(--arch-color-foreground)",
	"--color-muted": "var(--arch-color-surface-subtle)",
	"--color-muted-foreground": "var(--arch-color-muted-foreground)",
	"--color-faint-foreground": "var(--arch-color-faint-foreground)",
	"--color-border": "var(--arch-color-border)",
	"--color-border-subtle": "var(--arch-color-border-subtle)",
	"--color-input": "var(--arch-color-border)",
	"--color-ring": "var(--arch-color-selection)",
	"--color-surface": "var(--arch-color-surface)",
	"--color-surface-raised": "var(--arch-color-surface-raised)",
	"--color-surface-subtle": "var(--arch-color-surface-subtle)",
	"--color-surface-hover": "var(--arch-color-surface-hover)",
	"--color-card": "var(--arch-color-surface)",
	"--color-card-foreground": "var(--arch-color-foreground)",
	"--color-popover": "var(--arch-color-surface-raised)",
	"--color-popover-foreground": "var(--arch-color-foreground)",
	"--color-primary": "var(--arch-color-primary)",
	"--color-primary-hover": "var(--arch-color-primary-hover)",
	"--color-primary-subtle": "var(--arch-color-primary-subtle)",
	"--color-primary-foreground": "var(--arch-color-primary-foreground)",
	"--color-secondary": "var(--arch-color-surface-subtle)",
	"--color-secondary-foreground": "var(--arch-color-foreground)",
	"--color-accent": "var(--arch-color-primary)",
	"--color-accent-foreground": "var(--arch-color-primary-foreground)",
	"--color-destructive": "var(--arch-color-destructive)",
	"--color-destructive-subtle": "var(--arch-color-destructive-subtle)",
	"--color-warning": "var(--arch-color-warning)",
	"--color-warning-subtle": "var(--arch-color-warning-subtle)",
	"--color-status": "var(--arch-color-status)",
	"--color-status-foreground": "var(--arch-color-status-foreground)",
	"--color-status-subtle": "var(--arch-color-status-subtle)",
	"--color-offline": "var(--arch-color-offline)",
	"--color-path-focus-dim": "var(--arch-color-path-focus-dim)",
	"--font-sans": "var(--arch-font-ui)",
	"--font-mono": "var(--arch-font-technical)",
	"--font-weight-regular": "var(--arch-weight-regular)",
	"--font-weight-medium": "var(--arch-weight-medium)",
	"--font-weight-semibold": "var(--arch-weight-semibold)",
	"--font-weight-bold": "var(--arch-weight-bold)",
	"--tracking-wordmark": "var(--arch-wordmark-tracking)",
	"--text-kicker": "var(--arch-text-kicker-size)",
	"--text-kicker--line-height": "var(--arch-text-kicker-line)",
	"--text-technical": "var(--arch-text-technical-size)",
	"--text-technical--line-height": "var(--arch-text-technical-line)",
	"--text-body": "var(--arch-text-body-size)",
	"--text-body--line-height": "var(--arch-text-body-line)",
	"--text-control": "var(--arch-text-control-size)",
	"--text-control--line-height": "var(--arch-text-control-line)",
	"--text-title": "var(--arch-text-title-size)",
	"--text-title--line-height": "var(--arch-text-title-line)",
	"--text-primary": "var(--arch-text-primary-size)",
	"--text-primary--line-height": "var(--arch-text-primary-line)",
	"--radius-hairline": "var(--arch-radius-hairline)",
	"--radius-compact": "var(--arch-radius-compact)",
	"--radius-control": "var(--arch-radius-control)",
	"--radius-panel": "var(--arch-radius-panel)",
	"--radius-dialog": "var(--arch-radius-dialog)",
	"--radius-round": "var(--arch-radius-round)",
	"--spacing-rule": "var(--arch-space-rule)",
	"--spacing-compact": "var(--arch-space-compact)",
	"--spacing-grid-tight": "var(--arch-space-tight)",
	"--spacing-control": "var(--arch-space-control)",
	"--spacing-control-inline": "var(--arch-space-control-inline)",
	"--spacing-region": "var(--arch-space-region)",
	"--spacing-panel": "var(--arch-space-panel)",
	"--spacing-touch-target": "var(--arch-size-touch-target)",
	"--spacing-header": "var(--arch-size-header)",
	"--shadow-flat": "var(--arch-shadow-flat)",
	"--opacity-disabled-control": "var(--arch-opacity-disabled-control)",
	"--opacity-disabled-item": "var(--arch-opacity-disabled-item)",
	"--opacity-disabled-action": "var(--arch-opacity-disabled-action)",
	"--opacity-status-rest": "var(--arch-opacity-status-rest)",
	"--opacity-status-active": "var(--arch-opacity-status-active)",
	"--transition-duration-control": "var(--arch-duration-control)",
	"--transition-duration-status": "var(--arch-duration-status)",
	"--ease-control": "var(--arch-ease-control)",
	"--ease-status": "var(--arch-ease-status)",
	"--animate-status": "var(--arch-animation-status)",
} as const;

const colorCandidates = [
	"background",
	"foreground",
	"muted",
	"muted-foreground",
	"faint-foreground",
	"border",
	"border-subtle",
	"input",
	"ring",
	"surface",
	"surface-raised",
	"surface-subtle",
	"surface-hover",
	"card",
	"card-foreground",
	"popover",
	"popover-foreground",
	"primary",
	"primary-hover",
	"primary-subtle",
	"primary-foreground",
	"secondary",
	"secondary-foreground",
	"accent",
	"accent-foreground",
	"destructive",
	"destructive-subtle",
	"warning",
	"warning-subtle",
	"status",
	"status-foreground",
	"status-subtle",
	"offline",
	"path-focus-dim",
].map((name) => `bg-${name}`);

export const OWNED_CANDIDATES = [
	...colorCandidates,
	"font-sans",
	"font-mono",
	"font-regular",
	"font-medium",
	"font-semibold",
	"font-bold",
	"tracking-wordmark",
	"text-kicker",
	"text-technical",
	"text-body",
	"text-control",
	"text-title",
	"text-primary",
	"rounded-hairline",
	"rounded-compact",
	"rounded-control",
	"rounded-panel",
	"rounded-dialog",
	"rounded-round",
	"gap-rule",
	"gap-compact",
	"gap-grid-tight",
	"gap-control",
	"gap-control-inline",
	"gap-region",
	"gap-panel",
	"gap-touch-target",
	"gap-header",
	"shadow-flat",
	"opacity-disabled-control",
	"opacity-disabled-item",
	"opacity-disabled-action",
	"opacity-status-rest",
	"opacity-status-active",
	"duration-control",
	"duration-status",
	"ease-control",
	"ease-status",
	"animate-status",
] as const;

export type TailwindThemeGroup = {
	name: string;
	expectedCount: number;
	pattern: RegExp;
	refusalCandidate?: string;
	hardcodedCandidates?: readonly string[];
};

export const TAILWIND_THEME_GROUPS: readonly TailwindThemeGroup[] = [
	{ name: "colors", expectedCount: 288, pattern: /^--color-/, refusalCandidate: "bg-red-500" },
	{
		name: "font defaults",
		expectedCount: 6,
		pattern: /^--default-(?:font|mono)-/,
		refusalCandidate: "font-serif",
	},
	{
		name: "font families",
		expectedCount: 3,
		pattern: /^--font-(?:sans|serif|mono)$/,
		refusalCandidate: "font-serif",
	},
	{
		name: "font weights",
		expectedCount: 9,
		pattern: /^--font-weight-/,
		refusalCandidate: "font-black",
	},
	{
		name: "type scale",
		expectedCount: 26,
		pattern: /^--text-(?!shadow)/,
		refusalCandidate: "text-2xl",
	},
	{
		name: "tracking",
		expectedCount: 6,
		pattern: /^--tracking-/,
		refusalCandidate: "tracking-widest",
	},
	{ name: "leading", expectedCount: 5, pattern: /^--leading-/, refusalCandidate: "leading-tight" },
	{ name: "spacing", expectedCount: 1, pattern: /^--spacing$/, refusalCandidate: "gap-4" },
	{ name: "radii", expectedCount: 9, pattern: /^--radius/, refusalCandidate: "rounded-3xl" },
	{ name: "shadows", expectedCount: 9, pattern: /^--shadow/, refusalCandidate: "shadow-xl" },
	{
		name: "inset shadows",
		expectedCount: 3,
		pattern: /^--inset-shadow/,
		refusalCandidate: "inset-shadow-sm",
	},
	{
		name: "drop shadows",
		expectedCount: 7,
		pattern: /^--drop-shadow/,
		refusalCandidate: "drop-shadow-xl",
	},
	{
		name: "text shadows",
		expectedCount: 5,
		pattern: /^--text-shadow/,
		refusalCandidate: "text-shadow-lg",
	},
	{
		name: "transition defaults",
		expectedCount: 2,
		pattern: /^--default-transition-/,
		hardcodedCandidates: ["transition", "duration-150"],
	},
	{ name: "easing", expectedCount: 3, pattern: /^--ease-/, refusalCandidate: "ease-in-out" },
	{
		name: "animations",
		expectedCount: 4,
		pattern: /^--animate-/,
		refusalCandidate: "animate-pulse",
	},
	{ name: "blur", expectedCount: 8, pattern: /^--blur/, refusalCandidate: "blur-xl" },
	{
		name: "perspective",
		expectedCount: 5,
		pattern: /^--perspective/,
		refusalCandidate: "perspective-dramatic",
	},
	{ name: "aspect", expectedCount: 1, pattern: /^--aspect/, refusalCandidate: "aspect-video" },
	{ name: "breakpoints", expectedCount: 5, pattern: /^--breakpoint/, refusalCandidate: "sm:block" },
	{ name: "containers", expectedCount: 13, pattern: /^--container/, refusalCandidate: "max-w-7xl" },
	{
		name: "prose width",
		expectedCount: 1,
		pattern: /^--max-width/,
		refusalCandidate: "max-w-prose",
	},
] as const;

export const REFUSED_CANDIDATES = [
	...new Set(
		TAILWIND_THEME_GROUPS.flatMap((group) =>
			group.refusalCandidate === undefined ? [] : [group.refusalCandidate],
		),
	),
	"bg-token-that-does-not-exist",
] as const;

export const HARDCODED_TRANSITION_DEFAULT_CANDIDATES = ["transition", "duration-150"] as const;

export const TOKEN_FAMILY_MUTATIONS = [
	["typography", '"Archboard Onest"', '"Wrong Sans"'],
	["color", "#777b84", "#000"],
	["radius", "--arch-radius-control: 3px", "--arch-radius-control: 30px"],
	["spacing", "--arch-space-control: 8px", "--arch-space-control: 80px"],
	["elevation", "--arch-shadow-flat: none", "--arch-shadow-flat: 0 2px 4px #000"],
	["state", "--arch-opacity-disabled-control: 0.46", "--arch-opacity-disabled-control: 0.9"],
	["motion", "--arch-duration-control: 140ms", "--arch-duration-control: 999ms"],
	["dark", "#90949e", "#000"],
	[
		"accent alias",
		"--color-accent: var(--arch-color-primary)",
		"--color-accent: var(--arch-color-primary-subtle)",
	],
] as const;
