import type { DynamicApprovalCanonicalInput } from "../index.js";

export interface DynamicApprovalHashVector {
	readonly name: string;
	readonly input: DynamicApprovalCanonicalInput;
	readonly canonicalJson: string;
	readonly expectedHash: string;
}

export const DYNAMIC_APPROVAL_HASH_VECTORS: readonly DynamicApprovalHashVector[] = [
	{
		name: "create",
		input: {
			identity: {
				child: "child",
				epoch: "epoch",
				threadId: "caller",
				turnId: "caller-turn",
				callId: "create-call",
				namespace: "archboard_app",
				tool: "create_thread",
				manifestHash: "manifest-v1",
				operationId: "operation-create",
			},
			effect: {
				tool: "create_thread",
				arguments: { prompt: "Create a workhorse" },
				callerAuthority: "caller-authority",
				targetAuthority: null,
				contextAuthority: "context-authority",
				effectiveBoundary: null,
				mutationOperationId: "operation-create",
				initialTurnOperationId: "operation-create-turn",
				visualSummary: "Create a workhorse",
			},
		},
		canonicalJson: `{"identity":{"child":"child","epoch":"epoch","threadId":"caller","turnId":"caller-turn","callId":"create-call","namespace":"archboard_app","tool":"create_thread","manifestHash":"manifest-v1","operationId":"operation-create"},"effect":{"tool":"create_thread","arguments":{"prompt":"Create a workhorse"},"callerAuthority":"caller-authority","targetAuthority":null,"contextAuthority":"context-authority","effectiveBoundary":null,"mutationOperationId":"operation-create","initialTurnOperationId":"operation-create-turn","visualSummary":"Create a workhorse"}}`,
		expectedHash: "sha256:ceed7d0ca1a54419fdfd6c88438d9ea7743f95ad1cbff1d46b5bd8e4201775c3",
	},
	{
		name: "self-fork",
		input: {
			identity: {
				child: "child",
				epoch: "epoch",
				threadId: "caller",
				turnId: "caller-turn",
				callId: "fork-self-call",
				namespace: "archboard_app",
				tool: "fork_thread",
				manifestHash: "manifest-v1",
				operationId: "operation-fork-self",
			},
			effect: {
				tool: "fork_thread",
				arguments: { prompt: "Fork this turn", beforeTurnId: null, threadId: "caller" },
				callerAuthority: "caller-authority",
				targetAuthority: "caller-target-authority",
				contextAuthority: "context-authority",
				effectiveBoundary: { beforeTurnId: "caller-turn", relation: "self" },
				mutationOperationId: "operation-fork-self",
				initialTurnOperationId: "operation-fork-self-turn",
				visualSummary: "Fork the current caller",
			},
		},
		canonicalJson: `{"identity":{"child":"child","epoch":"epoch","threadId":"caller","turnId":"caller-turn","callId":"fork-self-call","namespace":"archboard_app","tool":"fork_thread","manifestHash":"manifest-v1","operationId":"operation-fork-self"},"effect":{"tool":"fork_thread","arguments":{"threadId":"caller","beforeTurnId":null,"prompt":"Fork this turn"},"callerAuthority":"caller-authority","targetAuthority":"caller-target-authority","contextAuthority":"context-authority","effectiveBoundary":{"relation":"self","beforeTurnId":"caller-turn"},"mutationOperationId":"operation-fork-self","initialTurnOperationId":"operation-fork-self-turn","visualSummary":"Fork the current caller"}}`,
		expectedHash: "sha256:bbc6b12117b27908febf9ddfee163a1c6910f8ead0e2f5b0e039260c77a04ede",
	},
	{
		name: "other-fork",
		input: {
			identity: {
				child: "child",
				epoch: "epoch",
				threadId: "caller",
				turnId: "caller-turn",
				callId: "fork-other-call",
				namespace: "archboard_app",
				tool: "fork_thread",
				manifestHash: "manifest-v1",
				operationId: "operation-fork-other",
			},
			effect: {
				tool: "fork_thread",
				arguments: {
					threadId: "other-target",
					beforeTurnId: "other-turn",
					prompt: "Review target",
				},
				callerAuthority: "caller-authority",
				targetAuthority: "target-authority",
				contextAuthority: "context-authority",
				effectiveBoundary: { relation: "other", beforeTurnId: "other-turn" },
				mutationOperationId: "operation-fork-other",
				initialTurnOperationId: "operation-fork-other-turn",
				visualSummary: "Fork the other target",
			},
		},
		canonicalJson: `{"identity":{"child":"child","epoch":"epoch","threadId":"caller","turnId":"caller-turn","callId":"fork-other-call","namespace":"archboard_app","tool":"fork_thread","manifestHash":"manifest-v1","operationId":"operation-fork-other"},"effect":{"tool":"fork_thread","arguments":{"threadId":"other-target","beforeTurnId":"other-turn","prompt":"Review target"},"callerAuthority":"caller-authority","targetAuthority":"target-authority","contextAuthority":"context-authority","effectiveBoundary":{"relation":"other","beforeTurnId":"other-turn"},"mutationOperationId":"operation-fork-other","initialTurnOperationId":"operation-fork-other-turn","visualSummary":"Fork the other target"}}`,
		expectedHash: "sha256:b02f6dd58a5209c76ebf479c04a8c0205715170338615e178e14a30ffe2a75f1",
	},
	{
		name: "send",
		input: {
			identity: {
				child: "child",
				epoch: "epoch",
				threadId: "caller",
				turnId: "caller-turn",
				callId: "send-call",
				namespace: "archboard_app",
				tool: "send_message_to_thread",
				manifestHash: "manifest-v1",
				operationId: "operation-send",
			},
			effect: {
				tool: "send_message_to_thread",
				arguments: { threadId: "other-target", prompt: "Please inspect the architecture" },
				callerAuthority: "caller-authority",
				targetAuthority: "target-authority",
				contextAuthority: "context-authority",
				effectiveBoundary: null,
				mutationOperationId: "operation-send",
				initialTurnOperationId: null,
				visualSummary: "Send a bounded message",
			},
		},
		canonicalJson: `{"identity":{"child":"child","epoch":"epoch","threadId":"caller","turnId":"caller-turn","callId":"send-call","namespace":"archboard_app","tool":"send_message_to_thread","manifestHash":"manifest-v1","operationId":"operation-send"},"effect":{"tool":"send_message_to_thread","arguments":{"threadId":"other-target","prompt":"Please inspect the architecture"},"callerAuthority":"caller-authority","targetAuthority":"target-authority","contextAuthority":"context-authority","effectiveBoundary":null,"mutationOperationId":"operation-send","initialTurnOperationId":null,"visualSummary":"Send a bounded message"}}`,
		expectedHash: "sha256:4e0083eb2809711541161b92b6a3caa9e5747ac7acad6117bb84676afa3c7b36",
	},
	{
		name: "fork-nullability",
		input: {
			identity: {
				child: "child",
				epoch: "epoch",
				threadId: "caller",
				turnId: "caller-turn",
				callId: "fork-nullability-call",
				namespace: "archboard_app",
				tool: "fork_thread",
				manifestHash: "manifest-v1",
				operationId: "operation-fork-nullability",
			},
			effect: {
				tool: "fork_thread",
				arguments: { threadId: "other-target", beforeTurnId: null, prompt: null },
				callerAuthority: "caller-authority",
				targetAuthority: "target-authority",
				contextAuthority: "context-authority",
				effectiveBoundary: { relation: "other", beforeTurnId: null },
				mutationOperationId: "operation-fork-nullability",
				initialTurnOperationId: null,
				visualSummary: "Fork without an initial turn",
			},
		},
		canonicalJson: `{"identity":{"child":"child","epoch":"epoch","threadId":"caller","turnId":"caller-turn","callId":"fork-nullability-call","namespace":"archboard_app","tool":"fork_thread","manifestHash":"manifest-v1","operationId":"operation-fork-nullability"},"effect":{"tool":"fork_thread","arguments":{"threadId":"other-target","beforeTurnId":null,"prompt":null},"callerAuthority":"caller-authority","targetAuthority":"target-authority","contextAuthority":"context-authority","effectiveBoundary":{"relation":"other","beforeTurnId":null},"mutationOperationId":"operation-fork-nullability","initialTurnOperationId":null,"visualSummary":"Fork without an initial turn"}}`,
		expectedHash: "sha256:3bcd6c3576e32272dd030a6b4d05cb9dcc9866be0438afdf562896a6a16134d0",
	},
	{
		name: "utf8-text",
		input: {
			identity: {
				child: "child",
				epoch: "epoch",
				threadId: "caller",
				turnId: "caller-turn",
				callId: "send-utf8-call",
				namespace: "archboard_app",
				tool: "send_message_to_thread",
				manifestHash: "manifest-v1",
				operationId: "operation-send-utf8",
			},
			effect: {
				tool: "send_message_to_thread",
				arguments: { threadId: "other-target", prompt: "Réviser l’architecture 🧭" },
				callerAuthority: "caller-authority",
				targetAuthority: "target-authority",
				contextAuthority: "context-authority",
				effectiveBoundary: null,
				mutationOperationId: "operation-send-utf8",
				initialTurnOperationId: null,
				visualSummary: "Envoyer à l’équipe 🧭",
			},
		},
		canonicalJson: `{"identity":{"child":"child","epoch":"epoch","threadId":"caller","turnId":"caller-turn","callId":"send-utf8-call","namespace":"archboard_app","tool":"send_message_to_thread","manifestHash":"manifest-v1","operationId":"operation-send-utf8"},"effect":{"tool":"send_message_to_thread","arguments":{"threadId":"other-target","prompt":"Réviser l’architecture 🧭"},"callerAuthority":"caller-authority","targetAuthority":"target-authority","contextAuthority":"context-authority","effectiveBoundary":null,"mutationOperationId":"operation-send-utf8","initialTurnOperationId":null,"visualSummary":"Envoyer à l’équipe 🧭"}}`,
		expectedHash: "sha256:21171e1fabd09dfdee097eeab40ac74e6ab1e659a026ded4d1bbe8244ecaa35b",
	},
];
