export const requestFieldOrder = ["identity", "effect", "effectHash", "createdAtMs", "expiresAtMs"];
export const identityFields = [
	"child",
	"epoch",
	"threadId",
	"turnId",
	"callId",
	"namespace",
	"tool",
	"manifestHash",
	"operationId",
];
export const effectFields = [
	"tool",
	"arguments",
	"callerAuthority",
	"targetAuthority",
	"contextAuthority",
	"effectiveBoundary",
	"mutationOperationId",
	"initialTurnOperationId",
	"visualSummary",
];
export const effectRows = [
	{
		tool: "create_thread",
		argumentFields: ["prompt"],
		nullableArguments: [],
		callerAuthority: "required",
		targetAuthority: "null",
		contextAuthority: "required",
		effectiveBoundary: "null",
		mutationOperationId: "identity.operationId",
		initialTurnOperationId: "fresh_required",
		visualSummaryLimitUtf8Bytes: 512,
	},
	{
		tool: "fork_thread",
		argumentFields: ["threadId", "beforeTurnId", "prompt"],
		nullableArguments: ["beforeTurnId", "prompt"],
		callerAuthority: "required",
		targetAuthority: "required",
		contextAuthority: "required",
		effectiveBoundary: "required",
		mutationOperationId: "identity.operationId",
		initialTurnOperationId: "fresh_when_prompt_else_null",
		visualSummaryLimitUtf8Bytes: 512,
	},
	{
		tool: "send_message_to_thread",
		argumentFields: ["threadId", "prompt"],
		nullableArguments: [],
		callerAuthority: "required",
		targetAuthority: "required",
		contextAuthority: "required",
		effectiveBoundary: "null",
		mutationOperationId: "identity.operationId",
		initialTurnOperationId: "null",
		visualSummaryLimitUtf8Bytes: 512,
	},
];
export const decisionOutcomes = ["approved", "declined", "expired", "cancelled", "disconnected"];
export const decisionCauses = [
	["approved", "person_approved", "revalidate_then_continue", "after_dispatch"],
	["declined", "person_declined", "none", "refused:approval_declined"],
	["expired", "deadline_reached", "none", "refused:expired"],
	["cancelled", "call_cancelled", "none", "approval_required"],
	["cancelled", "caller_turn_interrupted", "none", "approval_required"],
	["cancelled", "host_shutdown", "none", "approval_required"],
	["disconnected", "browser_disconnected", "none", "approval_required"],
	["disconnected", "child_disconnected", "none", "transport_not_delivered"],
].map(([outcome, cause, effect, toolResult]) => ({ outcome, cause, effect, toolResult }));
export const revalidationFailures = [
	["decision_identity_effect_or_manifest_changed", "invalid_call"],
	["child_replaced_or_disconnected", "stale_child"],
	["epoch_became_prior", "prior_epoch"],
	["caller_target_or_context_provenance_unproven", "unknown_provenance"],
	["caller_or_target_not_loaded", "not_loaded"],
	["caller_or_target_direct_input_not_true", "not_controllable"],
	["caller_or_target_system_error", "system_error"],
	["fork_or_send_target_became_active", "busy"],
	["relation_became_invalid_or_cyclic", "cycle"],
	["authority_token_effect_hash_or_operation_id_changed", "invalid_call"],
	["approval_expired_before_effect", "expired"],
].map(([condition, reason]) => ({ condition, reason }));
export const operationBoundaries = [
	{
		tool: "create_thread",
		boundary: "thread/start",
		operationId: "identity.operationId",
		reuse: ["effect.mutationOperationId", "epoch.operationId", "outer_result.operationId"],
	},
	{
		tool: "create_thread",
		boundary: "initial_turn/turn/start",
		operationId: "effect.initialTurnOperationId",
		reuse: [
			"epoch.operationId",
			"ArchboardContext.operation.id",
			"TurnStartParams.clientUserMessageId",
			"ok.value.initialTurn.operationId",
		],
	},
	{
		tool: "fork_thread",
		boundary: "thread/fork",
		operationId: "identity.operationId",
		reuse: ["effect.mutationOperationId", "epoch.operationId", "outer_result.operationId"],
	},
	{
		tool: "fork_thread",
		boundary: "optional_initial_turn/turn/start",
		operationId: "effect.initialTurnOperationId_or_null_without_prompt",
		reuse: [
			"epoch.operationId",
			"ArchboardContext.operation.id",
			"TurnStartParams.clientUserMessageId",
			"ok.value.initialTurn.operationId",
		],
	},
	{
		tool: "send_message_to_thread",
		boundary: "turn/start",
		operationId: "identity.operationId",
		reuse: [
			"effect.mutationOperationId",
			"epoch.operationId",
			"ArchboardContext.operation.id",
			"TurnStartParams.clientUserMessageId",
			"outer_result.operationId",
		],
	},
];
export const dispatcherOrder = [
	"validate_call_arguments_and_manifest",
	"resolve_and_classify_caller_target_and_context_authority",
	"issue_all_required_operation_ids",
	"freeze_immutable_effect_and_hash",
	"await_one_fresh_visual_approval",
	"revalidate_decision_caller_target_effect_context_and_ids",
	"read_one_fresh_ArchboardContext",
	"stage_one_local_epoch_transaction",
	"attempt_one_remote_rpc",
	"settle_durable_provenance_once",
	"construct_one_canonical_tool_result",
	"attempt_one_transport_response",
];
export const waitReleaseEvents = [
	"completion",
	"attention",
	"timeout",
	"cancellation",
	"interruption",
	"disconnect",
	"child_exit",
];
