// Preparing one copy of the skill for use outside the checkout.
//
// The tracked skill holds only what is authored. What an agent also needs when
// the skill is installed somewhere else — the generated JSON Schemas and the
// installation manual — is derived here into `references/generated/` of the
// copy, so that every link the skill makes to them is a relative link that
// works in the checkout and in any install alike. The same function prepares
// the checkout's own copy, the synced agent copies and an install's staging
// directory, so there is one answer to what a prepared skill contains.

import fs from "node:fs";
import path from "node:path";
import { generatedSchemas } from "@/runtime/skill-distribution/lib/schemas";

/** Where the generated files live inside a skill, relative to its root. */
const GENERATED_DIRECTORY = path.join("references", "generated");

/** The installation manual's name inside the generated directory. */
const INSTALL_DOCUMENT = "INSTALL.md";

/** What one preparation is given. */
interface PreparationSource {
	/** The archboard checkout root, where the canonical INSTALL.md lives. */
	readonly root: string;
	/** What to record as the source revision; the checkout's HEAD when absent. */
	readonly revision?: string | undefined;
}

/** What one preparation wrote. */
interface PreparedSkill {
	/** The generated directory, absolute. */
	readonly directory: string;
	/** Every file written, relative to the skill root, in the order written. */
	readonly files: readonly string[];
}

/**
 * The checkout revision the generated files are derived from.
 * @param root The checkout root.
 * @returns The commit and whether generated bytes include working-tree changes,
 * or "unknown" when git cannot say.
 */
function checkoutRevision(root: string): string {
	const asked = Bun.spawnSync(["git", "rev-parse", "HEAD"], {
		cwd: root,
		stdout: "pipe",
		stderr: "pipe",
	});
	const revision = asked.stdout.toString().trim();
	if (asked.exitCode !== 0 || revision === "") return "unknown";
	const status = Bun.spawnSync(["git", "status", "--porcelain"], {
		cwd: root,
		stdout: "pipe",
		stderr: "pipe",
	});
	return status.exitCode === 0 && status.stdout.length > 0
		? `${revision} (working tree modified)`
		: revision;
}

/**
 * The installation manual as the installed skill carries it: the canonical
 * text under a header that says where it came from, with the links that
 * pointed at the checkout's neighbours resolved to the checkout, since the
 * copy no longer sits beside them.
 * @param root The checkout root.
 * @param revision The revision being recorded.
 * @returns The document text.
 */
function installedInstallDocument(root: string, revision: string): string {
	const canonical = fs.readFileSync(path.join(root, INSTALL_DOCUMENT), "utf8");
	const resolved = canonical.replaceAll(
		/\]\((?!https?:|#|\/)([^)]+)\)/gu,
		(_match, target: string) => `](<${path.join(root, target)}>)`,
	);
	return (
		`<!-- Generated copy of ${path.join(root, INSTALL_DOCUMENT)} at revision ${revision}. ` +
		"Edit the canonical file in the archboard checkout; this copy is replaced on every install and sync. -->\n\n" +
		resolved
	);
}

/**
 * Prepares one skill directory: writes the generated schemas and the
 * installation-local manual into its `references/generated/` directory, replacing
 * whatever an earlier preparation left there.
 *
 * Deterministic for one source state, and free of side effects until called: the
 * schemas are rendered from the Zod authorities on each call, and nothing is
 * written anywhere else.
 * @param skill The skill directory to prepare, the tracked one or a copy.
 * @param source The checkout the derived files come from.
 * @returns What was written.
 */
function prepareSkillArtifacts(skill: string, source: PreparationSource): PreparedSkill {
	const directory = path.join(skill, GENERATED_DIRECTORY);
	fs.rmSync(directory, { recursive: true, force: true });
	fs.mkdirSync(directory, { recursive: true });
	const revision = source.revision ?? checkoutRevision(source.root);
	const files: string[] = [];
	for (const generated of generatedSchemas()) {
		fs.writeFileSync(
			path.join(directory, generated.file),
			`${JSON.stringify(generated.schema, null, "\t")}\n`,
		);
		files.push(path.join(GENERATED_DIRECTORY, generated.file));
	}
	fs.writeFileSync(
		path.join(directory, INSTALL_DOCUMENT),
		installedInstallDocument(source.root, revision),
	);
	files.push(path.join(GENERATED_DIRECTORY, INSTALL_DOCUMENT));
	return { directory, files };
}

export {
	GENERATED_DIRECTORY,
	INSTALL_DOCUMENT,
	prepareSkillArtifacts,
	type PreparationSource,
	type PreparedSkill,
};
