/** Supported client-to-server requests from the generated Codex 0.151.0 union. */
export const CLIENT_REQUEST_METHODS = [
	"initialize",
	"config/read",
	"configRequirements/read",
	"account/read",
	"account/login/start",
	"account/login/cancel",
	"account/logout",
	"model/list",
	"thread/start",
	"thread/fork",
	"thread/list",
	"thread/loaded/list",
	"thread/read",
	"thread/turns/list",
	"thread/items/list",
	"thread/delete",
	"thread/settings/update",
	"turn/start",
	"turn/steer",
	"turn/interrupt",
	"thread/queue/add",
	"thread/queue/list",
	"thread/queue/update",
	"thread/queue/delete",
	"thread/queue/reorder",
	"thread/queue/start",
	"thread/inject_items",
	"thread/realtime/start",
	"thread/realtime/appendText",
	"thread/realtime/appendSpeech",
	"thread/realtime/stop",
	"thread/timeline/list",
] as const;

/** Generated requests whose `params` value is exactly undefined and omitted on the wire. */
export const CLIENT_REQUEST_METHODS_WITHOUT_PARAMS = [
	"configRequirements/read",
	"account/logout",
] as const satisfies readonly ClientRequestMethod[];

/** Result decoders also own the currentTime/read reverse-request response alias. */
export const RESPONSE_METHODS = [...CLIENT_REQUEST_METHODS, "currentTime/read"] as const;

/** The only client notification emitted on the app-server connection. */
export const CLIENT_NOTIFICATION_METHODS = ["initialized"] as const;

/** Reverse requests the app-server may send to this client. */
export const SERVER_REQUEST_METHODS = [
	"item/commandExecution/requestApproval",
	"item/fileChange/requestApproval",
	"item/tool/requestUserInput",
	"mcpServer/elicitation/request",
	"item/permissions/requestApproval",
	"item/tool/call",
	"account/chatgptAuthTokens/refresh",
	"attestation/generate",
	"currentTime/read",
	"applyPatchApproval",
	"execCommandApproval",
] as const;

/** Server notification methods generated by Codex 0.151.0. */
export const SERVER_NOTIFICATION_METHODS = [
	"error",
	"thread/started",
	"thread/status/changed",
	"thread/archived",
	"thread/deleted",
	"thread/unarchived",
	"thread/closed",
	"thread/reverted",
	"skills/changed",
	"thread/name/updated",
	"thread/goal/updated",
	"thread/goal/cleared",
	"thread/queue/changed",
	"project/changed",
	"thread/project/updated",
	"thread/environment/connected",
	"thread/environment/disconnected",
	"thread/settings/updated",
	"thread/tokenUsage/updated",
	"turn/started",
	"hook/started",
	"turn/completed",
	"hook/completed",
	"turn/diff/updated",
	"turn/plan/updated",
	"item/started",
	"item/autoApprovalReview/started",
	"item/autoApprovalReview/completed",
	"autoApprovalReview/strictReviewRequired",
	"item/completed",
	"rawResponseItem/completed",
	"rawResponse/completed",
	"item/agentMessage/delta",
	"item/plan/delta",
	"command/exec/outputDelta",
	"process/outputDelta",
	"process/exited",
	"item/commandExecution/outputDelta",
	"item/commandExecution/terminalInteraction",
	"item/fileChange/outputDelta",
	"item/fileChange/patchUpdated",
	"serverRequest/resolved",
	"item/mcpToolCall/progress",
	"mcpServer/oauthLogin/completed",
	"mcpServer/startupStatus/updated",
	"mcpServer/event/stream/notification",
	"account/updated",
	"account/rateLimits/updated",
	"app/list/updated",
	"remoteControl/status/changed",
	"externalAgentConfig/import/progress",
	"externalAgentConfig/import/completed",
	"fs/changed",
	"item/reasoning/summaryTextDelta",
	"item/reasoning/summaryPartAdded",
	"item/reasoning/textDelta",
	"thread/compacted",
	"model/rerouted",
	"model/verification",
	"turn/moderationMetadata",
	"model/safetyBuffering/updated",
	"warning",
	"guardianWarning",
	"deprecationNotice",
	"configWarning",
	"fuzzyFileSearch/sessionUpdated",
	"fuzzyFileSearch/sessionCompleted",
	"thread/realtime/started",
	"thread/realtime/itemAdded",
	"thread/realtime/item/started",
	"thread/realtime/item/transcript/delta",
	"thread/realtime/item/completed",
	"thread/realtime/transcript/delta",
	"thread/realtime/transcript/done",
	"thread/realtime/outputAudio/delta",
	"thread/realtime/sdp",
	"thread/realtime/error",
	"thread/realtime/closed",
	"windows/worldWritableWarning",
	"windowsSandbox/setupCompleted",
	"account/login/completed",
] as const;

export type ResponseMethod = (typeof RESPONSE_METHODS)[number];
export type ClientRequestMethod = (typeof CLIENT_REQUEST_METHODS)[number];
export type ClientRequestMethodWithoutParams =
	(typeof CLIENT_REQUEST_METHODS_WITHOUT_PARAMS)[number];
export type ClientNotificationMethod = (typeof CLIENT_NOTIFICATION_METHODS)[number];
export type ServerRequestMethod = (typeof SERVER_REQUEST_METHODS)[number];
export type ServerNotificationMethod = (typeof SERVER_NOTIFICATION_METHODS)[number];

export function isClientRequestMethodWithoutParams(
	method: string,
): method is ClientRequestMethodWithoutParams {
	return (CLIENT_REQUEST_METHODS_WITHOUT_PARAMS as readonly string[]).includes(method);
}
