import type {
	CodexClientNotificationByMethod,
	CodexResponseByMethod,
	CodexServerNotificationParamsByMethod,
} from "@/shared/codex-app-server-contract";
import {
	CODEX_CLIENT_REQUEST_METHODS,
	CODEX_SERVER_REQUEST_METHODS,
} from "@/shared/codex-app-server-contract";

/** Supported client-to-server requests from the generated Codex 0.151.0 union. */
const CLIENT_REQUEST_METHODS = CODEX_CLIENT_REQUEST_METHODS;

/** Generated requests whose `params` value is exactly undefined and omitted on the wire. */
const CLIENT_REQUEST_METHODS_WITHOUT_PARAMS = [
	"configRequirements/read",
	"account/logout",
] as const satisfies readonly ClientRequestMethod[];

/** Result decoders also own the currentTime/read reverse-request response alias. */
const RESPONSE_METHODS = [
	...CLIENT_REQUEST_METHODS,
	"currentTime/read",
] as const satisfies readonly (keyof CodexResponseByMethod)[];

/** The only client notification emitted on the app-server connection. */
const CLIENT_NOTIFICATION_METHODS = [
	"initialized",
] as const satisfies readonly (keyof CodexClientNotificationByMethod)[];

/** Reverse requests the app-server may send to this client. */
const SERVER_REQUEST_METHODS = CODEX_SERVER_REQUEST_METHODS;

/** Server notification methods generated by Codex 0.151.0. */
const SERVER_NOTIFICATION_METHODS = [
	"error",
	"thread/started",
	"thread/status/changed",
	"thread/archived",
	"thread/deleted",
	"thread/unarchived",
	"thread/closed",
	"thread/reverted",
	"skills/changed",
	"thread/name/updated",
	"thread/goal/updated",
	"thread/goal/cleared",
	"thread/queue/changed",
	"project/changed",
	"thread/project/updated",
	"thread/environment/connected",
	"thread/environment/disconnected",
	"thread/settings/updated",
	"thread/tokenUsage/updated",
	"turn/started",
	"hook/started",
	"turn/completed",
	"hook/completed",
	"turn/diff/updated",
	"turn/plan/updated",
	"item/started",
	"item/autoApprovalReview/started",
	"item/autoApprovalReview/completed",
	"autoApprovalReview/strictReviewRequired",
	"item/completed",
	"rawResponseItem/completed",
	"rawResponse/completed",
	"item/agentMessage/delta",
	"item/plan/delta",
	"command/exec/outputDelta",
	"process/outputDelta",
	"process/exited",
	"item/commandExecution/outputDelta",
	"item/commandExecution/terminalInteraction",
	"item/fileChange/outputDelta",
	"item/fileChange/patchUpdated",
	"serverRequest/resolved",
	"item/mcpToolCall/progress",
	"mcpServer/oauthLogin/completed",
	"mcpServer/startupStatus/updated",
	"mcpServer/event/stream/notification",
	"account/updated",
	"account/rateLimits/updated",
	"app/list/updated",
	"remoteControl/status/changed",
	"externalAgentConfig/import/progress",
	"externalAgentConfig/import/completed",
	"fs/changed",
	"item/reasoning/summaryTextDelta",
	"item/reasoning/summaryPartAdded",
	"item/reasoning/textDelta",
	"thread/compacted",
	"model/rerouted",
	"model/verification",
	"turn/moderationMetadata",
	"model/safetyBuffering/updated",
	"warning",
	"guardianWarning",
	"deprecationNotice",
	"configWarning",
	"fuzzyFileSearch/sessionUpdated",
	"fuzzyFileSearch/sessionCompleted",
	"thread/realtime/started",
	"thread/realtime/itemAdded",
	"thread/realtime/item/started",
	"thread/realtime/item/transcript/delta",
	"thread/realtime/item/completed",
	"thread/realtime/transcript/delta",
	"thread/realtime/transcript/done",
	"thread/realtime/outputAudio/delta",
	"thread/realtime/sdp",
	"thread/realtime/error",
	"thread/realtime/closed",
	"windows/worldWritableWarning",
	"windowsSandbox/setupCompleted",
	"account/login/completed",
] as const satisfies readonly (keyof CodexServerNotificationParamsByMethod)[];

type ResponseMethod = (typeof RESPONSE_METHODS)[number];
type ClientRequestMethod = (typeof CLIENT_REQUEST_METHODS)[number];
type ClientRequestMethodWithoutParams = (typeof CLIENT_REQUEST_METHODS_WITHOUT_PARAMS)[number];
type ClientNotificationMethod = (typeof CLIENT_NOTIFICATION_METHODS)[number];
type ServerRequestMethod = (typeof SERVER_REQUEST_METHODS)[number];
type ServerNotificationMethod = (typeof SERVER_NOTIFICATION_METHODS)[number];

/**
 *
 */
function isClientRequestMethodWithoutParams(
	method: string,
): method is ClientRequestMethodWithoutParams {
	return (CLIENT_REQUEST_METHODS_WITHOUT_PARAMS as readonly string[]).includes(method);
}

export {
	CLIENT_REQUEST_METHODS,
	CLIENT_REQUEST_METHODS_WITHOUT_PARAMS,
	RESPONSE_METHODS,
	CLIENT_NOTIFICATION_METHODS,
	SERVER_REQUEST_METHODS,
	SERVER_NOTIFICATION_METHODS,
	type ResponseMethod,
	type ClientRequestMethod,
	type ClientRequestMethodWithoutParams,
	type ClientNotificationMethod,
	type ServerRequestMethod,
	type ServerNotificationMethod,
	isClientRequestMethodWithoutParams,
};
