import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import { describe, expect, test } from "bun:test";
import { API } from "typescript/unstable/async";
import { namespaceImportMirror } from "./support/codex-protocol-fixtures.js";

const repoRoot = path.resolve(import.meta.dir, "../../..");
const checker = path.join(repoRoot, "scripts/check-codex-protocol-fingerprint-corpus.ts");

function runChecker(corpusPath?: string): Error | undefined {
	try {
		execFileSync(
			"bun",
			corpusPath
				? [checker, "--corpus", corpusPath]
				: ["run", "check:codex-protocol-fingerprint-corpus"],
			{
				cwd: repoRoot,
				encoding: "utf8",
			},
		);
		return undefined;
	} catch (error) {
		return error as Error;
	}
}

const GENERATED_HEADER =
	"// GENERATED CODE! DO NOT MODIFY BY HAND!\n\n// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this generated file manually.";

async function diagnosticsFor(projectRoot: string, file: string): Promise<readonly unknown[]> {
	const compiler = new API({ cwd: projectRoot });
	try {
		const snapshot = await compiler.updateSnapshot({
			openProjects: [path.join(projectRoot, "tsconfig.json")],
			openFiles: [file],
		});
		const project = await snapshot.getDefaultProjectForFile(file);
		if (!project) throw new Error("TypeScript did not open the oracle project");
		return [
			...(await project.program.getSyntacticDiagnostics(file)),
			...(await project.program.getSemanticDiagnostics(file)),
		];
	} finally {
		void compiler.close();
	}
}

describe("Codex protocol fingerprint corpus", () => {
	test("regenerates every fingerprint from the pinned project-local generator", () => {
		expect(runChecker()).toBeUndefined();
	});

	test("rejects corruption in an otherwise unused fingerprint", () => {
		const temporaryRoot = fs.mkdtempSync(
			path.join(process.env.TMPDIR ?? "/tmp", "archboard-codex-corpus-"),
		);
		const temporaryCorpus = path.join(temporaryRoot, "corpus.json");
		try {
			const original = fs.readFileSync(
				path.join(
					repoRoot,
					"tests/system/repository-policy/support/codex-protocol-fingerprint-corpus.json",
				),
				"utf8",
			);
			const corrupted = JSON.parse(original) as { entries: Record<string, string[]> };
			const firstPath = Object.keys(corrupted.entries)[0];
			if (!firstPath) throw new Error("Corpus is empty");
			const firstTokens = corrupted.entries[firstPath];
			if (!firstTokens) throw new Error(`Corpus entry ${firstPath} is empty`);
			firstTokens[0] = "corrupt:unused-token";
			fs.writeFileSync(temporaryCorpus, `${JSON.stringify(corrupted, null, "\t")}\n`);
			const failure = runChecker(temporaryCorpus);
			expect(failure).toBeInstanceOf(Error);
			expect((failure as Error & { stderr?: Buffer }).stderr?.toString()).toContain(
				"does not match",
			);
		} finally {
			fs.rmSync(temporaryRoot, { recursive: true, force: true });
		}
	});

	test("keeps namespace mirror imports resolvable", async () => {
		const temporaryRoot = fs.mkdtempSync(path.join(os.tmpdir(), "archboard-codex-mirror-"));
		try {
			const source = `${GENERATED_HEADER}\n\nimport type { AbsolutePathBuf } from "../AbsolutePathBuf";\n// AbsolutePathBuf stays in comments.\nexport type Thread = { cwd: AbsolutePathBuf };\nexport const label = "AbsolutePathBuf";\n`;
			const mirror = namespaceImportMirror(source, GENERATED_HEADER);
			const entry = path.join(temporaryRoot, "v2", "Thread.ts");
			fs.mkdirSync(path.dirname(entry), { recursive: true });
			fs.writeFileSync(entry, mirror);
			fs.writeFileSync(
				path.join(temporaryRoot, "AbsolutePathBuf.ts"),
				"export type AbsolutePathBuf = string;\n",
			);
			expect(mirror).toContain(
				'import type * as NamespaceAbsolutePathBuf from "../AbsolutePathBuf";',
			);
			expect(mirror).toContain("// AbsolutePathBuf stays in comments.");
			expect(mirror).toContain('label = "AbsolutePathBuf"');
			expect(mirror).not.toContain("NamespaceAbsolutePathBuf.AbsolutePathBuf.AbsolutePathBuf");
			expect(await diagnosticsFor(repoRoot, entry)).toEqual([]);
		} finally {
			fs.rmSync(temporaryRoot, { recursive: true, force: true });
		}
	});
});
