import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

import { describe, expect, test } from "bun:test";

import {
	discoverNativeTests,
	inspectTestInventory,
	type InventoryInput,
} from "./support/test-inventory.js";

const repoRoot = path.resolve(import.meta.dir, "../../..");
const GENERATED_ROOT = "src/runtime/codex-protocol/generated/";
const ADAPTER_PATH = "src/runtime/codex-protocol/index.ts";
const CONFORMANCE_OWNER_PATH = "src/runtime/codex-protocol/conformance.ts";
const ROOT_CONFORMANCE_OWNER_PATH =
	"tests/system/repository-policy/codex-protocol-conformance.test.ts";
const POLICY_PATH = "tests/system/repository-policy/codex-protocol-boundary.test.ts";

const GENERATED_HEADER =
	"// GENERATED CODE! DO NOT MODIFY BY HAND!\n\n// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.";
const GENERATED_BINDING_NAMES = new Set([
	"ClientNotification",
	"ClientRequest",
	"ServerNotification",
	"ServerRequest",
]);

const ALLOWED_GENERATED_IMPORTERS = new Map([
	[ADAPTER_PATH, "the public codex-protocol adapter is the sole consumer boundary"],
	[GENERATED_ROOT, "generated files may import their own generated peers"],
]);

const TEMP_GENERATION_OWNERS = new Map([
	[
		CONFORMANCE_OWNER_PATH,
		"the module conformance owner generates and compares only in a temporary directory",
	],
	[
		ROOT_CONFORMANCE_OWNER_PATH,
		"the root conformance owner uses disposable generator fixtures only",
	],
]);

interface SourceFile {
	readonly path: string;
	readonly source: string;
	readonly tracked?: boolean;
}

interface OwnershipFinding {
	readonly file: string;
	readonly reason: string;
	readonly message: string;
}

interface Token {
	readonly kind: "identifier" | "punctuation" | "string";
	readonly value: string;
}

function isIdentifierStart(character: string | undefined): boolean {
	return character !== undefined && /[$A-Z_a-z]/u.test(character);
}

function isIdentifierPart(character: string | undefined): boolean {
	return character !== undefined && /[$0-9A-Z_a-z]/u.test(character);
}

function sourceTokens(source: string): Token[] {
	const tokens: Token[] = [];
	let index = 0;
	while (index < source.length) {
		const character = source[index];
		if (/\s/u.test(character ?? "")) {
			index += 1;
			continue;
		}
		if (character === "/" && source[index + 1] === "/") {
			index += 2;
			while (index < source.length && source[index] !== "\n") index += 1;
			continue;
		}
		if (character === "/" && source[index + 1] === "*") {
			index += 2;
			while (index < source.length && !(source[index] === "*" && source[index + 1] === "/"))
				index += 1;
			index += 2;
			continue;
		}
		if (character === "`" || character === '"' || character === "'") {
			const quote = character;
			index += 1;
			const start = index;
			let value = "";
			while (index < source.length) {
				if (source[index] === "\\") {
					value += source.slice(start, index);
					value += source[index + 1] ?? "";
					index += 2;
					continue;
				}
				if (source[index] === quote) break;
				index += 1;
			}
			if (quote !== "`") tokens.push({ kind: "string", value: value + source.slice(start, index) });
			if (source[index] === quote) index += 1;
			continue;
		}
		if (isIdentifierStart(character)) {
			const start = index;
			index += 1;
			while (isIdentifierPart(source[index])) index += 1;
			tokens.push({ kind: "identifier", value: source.slice(start, index) });
			continue;
		}
		tokens.push({ kind: "punctuation", value: character ?? "" });
		index += 1;
	}
	return tokens;
}

function importedSpecifiers(source: string): string[] {
	const tokens = sourceTokens(source);
	const specifiers: string[] = [];
	for (let index = 0; index < tokens.length; index += 1) {
		const token = tokens[index];
		if (token?.kind !== "identifier") continue;
		if (token.value === "import" && tokens[index - 1]?.value === ".") continue;
		if (token.value !== "import" && token.value !== "export" && token.value !== "require") continue;

		const next = tokens[index + 1];
		if (token.value === "require") {
			if (next?.value === "(" && tokens[index + 2]?.kind === "string")
				specifiers.push(tokens[index + 2]?.value ?? "");
			continue;
		}
		if (next?.kind === "string") {
			specifiers.push(next.value);
			continue;
		}
		if (next?.value === "(") {
			if (tokens[index + 2]?.kind === "string") specifiers.push(tokens[index + 2]?.value ?? "");
			continue;
		}
		for (let cursor = index + 1; cursor < Math.min(tokens.length, index + 80); cursor += 1) {
			const candidate = tokens[cursor];
			if (candidate?.value === ";") break;
			if (candidate?.value === "from" && tokens[cursor + 1]?.kind === "string") {
				specifiers.push(tokens[cursor + 1]?.value ?? "");
				break;
			}
		}
	}
	return specifiers;
}

function normalizeRepositoryPath(value: string): string {
	return value.replaceAll("\\", "/").replace(/^\.\//u, "");
}

function isCanonicalGeneratedPath(filePath: string): boolean {
	return normalizeRepositoryPath(filePath).startsWith(GENERATED_ROOT);
}

function generatedPathFromImport(importer: string, specifier: string): string | undefined {
	if (!specifier.startsWith(".")) return undefined;
	const absolute = path.resolve(repoRoot, path.dirname(importer), specifier);
	const relative = normalizeRepositoryPath(path.relative(repoRoot, absolute));
	const withoutExtension = relative.replace(/\.(?:[cm]?js|tsx?)$/u, "");
	return withoutExtension.includes("/generated/") ? withoutExtension : undefined;
}

function generatedBindingSource(source: string): boolean {
	return source.startsWith(GENERATED_HEADER);
}

function handwrittenMirrorSource(source: string): boolean {
	const tokens = sourceTokens(source);
	return tokens.some((token, index) => {
		if (token.value !== "export" || tokens[index + 1]?.value !== "type") {
			if (token.value !== "export" || tokens[index + 1]?.value !== "interface") return false;
		}
		const name = tokens[index + 2];
		if (name?.kind !== "identifier" || !GENERATED_BINDING_NAMES.has(name.value)) return false;
		const declarationEnd = tokens[index + 3];
		return (
			declarationEnd?.value === "{" ||
			(declarationEnd?.value === "=" && tokens[index + 4]?.value === "{")
		);
	});
}

function ownershipFindings(files: readonly SourceFile[]): OwnershipFinding[] {
	const findings: OwnershipFinding[] = [];
	for (const file of files) {
		const canonical = isCanonicalGeneratedPath(file.path);
		const generated = generatedBindingSource(file.source);
		const mirror = !generated && handwrittenMirrorSource(file.source);
		if (canonical && !generated) {
			findings.push({
				file: file.path,
				reason: "handwritten mirror",
				message:
					"the generated directory accepts only the exact ts-rs output; put handwritten schemas behind the public adapter",
			});
		}
		if (generated && !canonical) {
			findings.push({
				file: file.path,
				reason: "generated tree outside canonical directory",
				message: `move this binding under ${GENERATED_ROOT}, which is the only ignored generated directory`,
			});
		}
		if (canonical && generated && file.tracked) {
			findings.push({
				file: file.path,
				reason: "committed generated output",
				message: "remove it from Git and regenerate into the ignored directory",
			});
		}
		if (mirror && !canonical) {
			findings.push({
				file: file.path,
				reason: "handwritten mirror",
				message:
					"delete the mirror and consume decoded values through the public codex-protocol adapter",
			});
		}

		for (const specifier of importedSpecifiers(file.source)) {
			const target = generatedPathFromImport(file.path, specifier);
			if (!target) continue;
			const allowedReason =
				ALLOWED_GENERATED_IMPORTERS.get(file.path) ??
				(canonical ? ALLOWED_GENERATED_IMPORTERS.get(GENERATED_ROOT) : undefined);
			if (allowedReason) continue;
			findings.push({
				file: file.path,
				reason: "deep import",
				message: `import ${target} only through ${ADAPTER_PATH}; ${TEMP_GENERATION_OWNERS.get(CONFORMANCE_OWNER_PATH) ?? "the conformance owner"} does not authorize checkout imports`,
			});
		}
	}
	return findings;
}

function repositorySourceFiles(): SourceFile[] {
	const tracked = new Set(
		execFileSync("git", ["ls-files", "-z"], { cwd: repoRoot, encoding: "utf8" })
			.split("\0")
			.filter(Boolean),
	);
	const paths = new Set<string>();
	for (const pattern of ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cjs"]) {
		for (const file of new Bun.Glob(pattern).scanSync({ cwd: repoRoot, onlyFiles: true })) {
			if (/(?:^|\/)(?:\.git|backlog|dist|node_modules)(?:\/|$)/u.test(file)) continue;
			paths.add(normalizeRepositoryPath(file));
		}
	}
	return [...paths].toSorted().map((file) => ({
		path: file,
		source: fs.readFileSync(path.join(repoRoot, file), "utf8"),
		tracked: tracked.has(file),
	}));
}

function generatedDirectoryIsIgnored(): boolean {
	try {
		execFileSync(
			"git",
			["check-ignore", "--no-index", "--quiet", "--", `${GENERATED_ROOT}probe.ts`],
			{
				cwd: repoRoot,
			},
		);
		return true;
	} catch {
		return false;
	}
}

function syntheticGeneratedFile(filePath: string, tracked = false): SourceFile {
	return {
		path: filePath,
		source: `${GENERATED_HEADER}\n\nexport type ClientRequest = { method: "fixture" };\n`,
		tracked,
	};
}

function inventoryInput(): InventoryInput {
	const packageJson = JSON.parse(fs.readFileSync(path.join(repoRoot, "package.json"), "utf8")) as {
		scripts: Record<string, string>;
	};
	return {
		repoRoot,
		scripts: packageJson.scripts,
		nativeTests: discoverNativeTests(repoRoot),
	};
}

describe("Codex protocol generated ownership policy", () => {
	test("keeps the exact generated directory ignored and the adapter boundary explicit", () => {
		expect(generatedDirectoryIsIgnored()).toBeTrue();
		expect(ALLOWED_GENERATED_IMPORTERS.get(ADAPTER_PATH)).toContain(
			"public codex-protocol adapter",
		);
		expect(TEMP_GENERATION_OWNERS.get(CONFORMANCE_OWNER_PATH)).toContain("temporary directory");
		expect(TEMP_GENERATION_OWNERS.get(ROOT_CONFORMANCE_OWNER_PATH)).toContain(
			"disposable generator fixtures",
		);

		const allowed = ownershipFindings([
			syntheticGeneratedFile(`${GENERATED_ROOT}ClientRequest.ts`),
			{
				path: ADAPTER_PATH,
				source: 'export type { ClientRequest } from "./generated/ClientRequest.js";\n',
			},
			syntheticGeneratedFile(`${GENERATED_ROOT}Thread.ts`),
			{
				path: CONFORMANCE_OWNER_PATH,
				source: 'const generatedRoot = "/tmp/archboard-codex-generated-fixture";\n',
			},
		]);
		expect(allowed).toEqual([]);
	});

	test("rejects committed output, alternate trees, mirrors, and every consumer bypass", () => {
		const forbidden: SourceFile[] = [
			syntheticGeneratedFile(`${GENERATED_ROOT}ClientRequest.ts`, true),
			syntheticGeneratedFile("src/runtime/other/generated/ClientRequest.ts"),
			{
				path: "src/runtime/codex-protocol/generated/Handwritten.ts",
				source: 'export type ClientRequest = { method: "fixture" };\n',
			},
			{
				path: "src/runtime/codex-protocol-mirror.ts",
				source: "export interface ServerRequest { method: string; }\n",
			},
		];
		for (const importer of [
			"src/runtime/consumer.ts",
			"src/server/consumer.ts",
			"src/ui/consumer.tsx",
			"scripts/consumer.ts",
			"tests/system/consumer.test.ts",
		]) {
			forbidden.push({
				path: importer,
				source:
					'import type { ClientRequest } from "../runtime/codex-protocol/generated/ClientRequest.js";\n',
			});
		}

		const findings = ownershipFindings(forbidden);
		expect(findings).toHaveLength(9);
		for (const finding of findings) {
			expect(finding.file).not.toBe(POLICY_PATH);
			expect(finding.message).toMatch(
				/(?:move|remove|only the exact|only through|consume decoded)/u,
			);
		}
		expect(findings.map(({ reason }) => reason)).toEqual([
			"committed generated output",
			"generated tree outside canonical directory",
			"handwritten mirror",
			"handwritten mirror",
			"deep import",
			"deep import",
			"deep import",
			"deep import",
			"deep import",
		]);
	});

	test("does not confuse ordinary generated names or string fixtures with bindings", () => {
		const ordinary = ownershipFindings([
			{
				path: "src/runtime/ordinary-generated-cache.ts",
				source: "export type GeneratedCache = Map<string, string>;\n",
			},
			{
				path: "src/ui/codex-realtime/tests/contract.test.ts",
				source:
					"const fixture = 'import type { Event } from \"./generated/codex-protocol.js\";';\n",
			},
		]);
		expect(ordinary).toEqual([]);
	});

	test("the pre-policy forbidden fixture fails through the repository owner", () => {
		const forbidden = ownershipFindings([
			{
				path: "src/server/codex-session.ts",
				source:
					'import { ClientRequest } from "../runtime/codex-protocol/generated/ClientRequest.js";\n',
			},
		]);
		expect(forbidden).toEqual([
			expect.objectContaining({
				file: "src/server/codex-session.ts",
				reason: "deep import",
			}),
		]);
	});

	test("is reached once by the existing repository inventory", () => {
		const inventory = inventoryInput();
		expect(inventory.nativeTests).toContain(POLICY_PATH);
		const result = inspectTestInventory(inventory);
		expect(result.errors).toEqual([]);
		expect(result.nativeLanes.get("test:repository")).toEqual(
			expect.arrayContaining([POLICY_PATH]),
		);
		expect(
			result.nativeLanes.get("test:repository")?.filter((file) => file === POLICY_PATH),
		).toHaveLength(1);
	});

	test("the real checkout has no generated binding outside the owner", () => {
		const findings = ownershipFindings(repositorySourceFiles()).filter(
			({ file }) => file !== POLICY_PATH,
		);
		expect(findings).toEqual([]);
	});
});
